const fs=require('fs'),assert=require('assert/strict'),{chromium}=require('playwright'),{pathToFileURL}=require('url'),path=require('path'),D=require('../data'),E=require('../engine');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{const p=await b.newPage({viewport:{width:1366,height:768}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(pathToFileURL(path.resolve('sv_tavern.html')).href);await p.locator('[data-action="start"]').click();const s=E.create('goblin',345,'hard',['royal','forest','rune','night']);s.hp=27;s.armor=7;s.gold=11;s.tier=6;s.round=12;s.board=['royal2','forest6','rune6','night16','neutral14','royal14','forest4'].map(id=>E.make(s,id));s.hand=['fairy','coin','grandBlessing','fairy','coin','fairy','royal2','rune6','fairy','coin'].map(id=>E.make(s,id));s.opponents[0].hero='goblin';s.opponents[0].name='哥布林';await p.locator('[data-action="menu"]').click();await p.locator('#save-file').setInputFiles({name:'qa.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});await p.locator('.modal').waitFor({state:'detached'});assert.equal((await p.evaluate(()=>TavernUI.getState())).opponents[0].name,'邦妮');
for(const [key,value] of Object.entries({hp:'27 / 40',armor:'7',gold:'11',tier:'6 本',round:'12 回合'}))assert.equal((await p.locator(`[data-resource="${key}"] strong`).innerText()).trim(),value);
assert((await p.locator('.fight-btn').boundingBox()).y+(await p.locator('.fight-btn').boundingBox()).height<=768);await p.screenshot({path:'dusk-tavern/qa/leaders-desktop.png',fullPage:true});console.log('desktop geometry',await p.evaluate(()=>({height:innerHeight,body:document.documentElement.scrollHeight,fight:document.querySelector('.fight-btn').getBoundingClientRect().bottom,hand:document.querySelector('.hand-row').getBoundingClientRect().bottom})));
await p.locator('[data-action="catalog"]').click();assert.equal(await p.locator('.catalog-entry').count(),D.cards.length+D.spells.length+D.amulets.length);assert.equal(await p.locator('[data-action="filter"]').count(),4);
await p.locator('[data-action="catalog-section"][data-id="hero"]').click();assert.equal(await p.locator('.catalog-entry').count(),22);assert.equal(await p.locator('#catalog-tier').count(),0);await p.locator('[data-action="catalog-card"][data-id="goblin"]').click();assert.equal(await p.locator('.catalog-card-body h2').innerText(),'邦妮');assert.equal(await p.locator('.leader-source').getAttribute('href'),'https://svgdb.me/leaders/2602');await p.locator('[data-action="catalog-back"]').click();
assert.equal(await p.evaluate(async()=>{let result=true;for(const h of TavernData.heroes){const i=new Image();i.src=TAVERN_ASSETS[h.art];await i.decode();result&&=i.naturalWidth>0&&!!h.leaderId;}return result;}),true);await p.screenshot({path:'dusk-tavern/qa/leaders-catalog.png'});
await p.locator('#catalog-search').fill('邦妮');assert.equal(await p.locator('.catalog-entry').count(),1);await p.locator('[data-action="catalog-section"][data-id="token"]').click();assert.equal(await p.locator('.catalog-entry').count(),D.tokens.length);await p.locator('[data-action="catalog-card"][data-id="fairy"]').click();assert.match(await p.locator('.catalog-note').first().innerText(),/可以三连/);await p.locator('.modal-close').click();
if(await p.locator('.modal-close').count())await p.locator('.modal-close').click();await p.locator('.modal').waitFor({state:'detached'});await p.setViewportSize({width:390,height:844});await p.evaluate(()=>scrollTo(0,document.body.scrollHeight));for(const key of ['hp','armor','gold','tier','round']){const box=await p.locator(`[data-resource="${key}"]`).boundingBox();assert(box.y>=0&&box.y+box.height<=112);}assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'dusk-tavern/qa/leaders-mobile.png'});await p.locator('[data-action="catalog"]').click();assert((await p.locator('.overlay').boundingBox()).y>=112);assert((await p.locator('[data-resource="hp"]').boundingBox()).y>=0);await p.screenshot({path:'dusk-tavern/qa/leaders-mobile-catalog.png'});assert.deepEqual(errors,[]);console.log('PASS: 22 official portraits; catalog sections/search/detail; save compatibility; exact desktop/mobile sticky resources; no browser errors');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
