(function(root){'use strict';
function random(seed){let s=seed|0;return()=>{s+=0x6D2B79F5;let t=Math.imul(s^s>>>15,1|s);t^=t+Math.imul(t^t>>>7,61|t);return((t^t>>>14)>>>0)/4294967296}}
function clip(poly,a,b,c){const out=[];for(let k=0;k<poly.length;k++){const p=poly[k],q=poly[(k+1)%poly.length],u=p.x*a+p.y*b-c,v=q.x*a+q.y*b-c;if(u<=.00001)out.push(p);if((u<0)!==(v<0)){const t=u/(u-v);out.push({x:p.x+(q.x-p.x)*t,y:p.y+(q.y-p.y)*t})}}return out}
function build(width,height,count,pixels,seed=1,progress=()=>{}){const rand=random(seed),sites=[],lum=(x,y)=>{let i=(Math.max(0,Math.min(height-1,y|0))*width+Math.max(0,Math.min(width-1,x|0)))*4;return pixels?(pixels[i]*.2126+pixels[i+1]*.7152+pixels[i+2]*.0722)/255:0};
for(let k=0;k<count;k++){let candidate;for(let tries=0;tries<35;tries++){let x=rand()*width,y=rand()*height,edge=Math.abs(lum(x+2,y)-lum(x-2,y))+Math.abs(lum(x,y+2)-lum(x,y-2));candidate={x,y};if(rand()<.45+edge*2)break}sites.push(candidate)}
const size=Math.sqrt(width*height/count)*2,cols=Math.ceil(width/size),rows=Math.ceil(height/size),buckets=Array.from({length:cols*rows},()=>[]);sites.forEach((p,i)=>buckets[Math.min(rows-1,Math.floor(p.y/size))*cols+Math.min(cols-1,Math.floor(p.x/size))].push(i));
const cells=[];for(let i=0;i<sites.length;i++){const a=sites[i];let poly=[{x:0,y:0},{x:width,y:0},{x:width,y:height},{x:0,y:height}];let gx=Math.floor(a.x/size),gy=Math.floor(a.y/size);for(let ring=0;ring<Math.max(cols,rows);ring++){let left=Math.max(0,gx-ring),right=Math.min(cols-1,gx+ring),top=Math.max(0,gy-ring),bottom=Math.min(rows-1,gy+ring);for(let y=top;y<=bottom;y++)for(let x=left;x<=right;x++){if(ring>0&&Math.max(Math.abs(x-gx),Math.abs(y-gy))!==ring)continue;for(let j of buckets[y*cols+x]){if(j===i)continue;const b=sites[j];poly=clip(poly,2*(b.x-a.x),2*(b.y-a.y),b.x*b.x+b.y*b.y-a.x*a.x-a.y*a.y);if(poly.length<3)break}}if(poly.length<3)break;let radius=Math.sqrt(Math.max(...poly.map(p=>(p.x-a.x)**2+(p.y-a.y)**2)));let outside=Math.min(left>0?a.x-left*size:Infinity,right<cols-1?(right+1)*size-a.x:Infinity,top>0?a.y-top*size:Infinity,bottom<rows-1?(bottom+1)*size-a.y:Infinity);if(outside>2*radius+.001)break}
if(i%500===0)progress(i/count);
if(poly.length<3)continue;const x0=Math.floor(Math.min(...poly.map(p=>p.x))),x1=Math.ceil(Math.max(...poly.map(p=>p.x))),y0=Math.floor(Math.min(...poly.map(p=>p.y))),y1=Math.ceil(Math.max(...poly.map(p=>p.y)));let color=[0,0,0],n=0;const sample=(x,y)=>{if(!pixels)return;let j=(Math.max(0,Math.min(height-1,y|0))*width+Math.max(0,Math.min(width-1,x|0)))*4;for(let k=0;k<3;k++)color[k]+=pixels[j+k];n++};sample(a.x,a.y);for(let p of poly)sample(a.x*.65+p.x*.35,a.y*.65+p.y*.35);color=n?color.map(v=>Math.round(v/n)):[120,160,190];cells.push({poly,x:a.x,y:a.y,x0,y0,x1,y1,color})}return cells}
function area(poly){return Math.abs(poly.reduce((s,p,i)=>{const q=poly[(i+1)%poly.length];return s+p.x*q.y-q.x*p.y},0)/2)}
root.GlassGeometry={build,random,area};if(typeof module!=='undefined')module.exports=root.GlassGeometry;
})(typeof globalThis!=='undefined'?globalThis:this);
