const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const E=require('./engine.js'),S=require('./semantics.js');
let id=0;const card=(name,text,extra={})=>({id:++id,name,type:4,class:0,cost:1,rarity:1,attack:0,health:0,tribes:[],text,evolvedText:'',effects:[],...extra});
const a=card('甲','选择自己的战场上的1个随从，使其+1/+1。',{token:true});
const b=card('乙',a.text,{token:true});
const c=card('丙','对对手的主战者造成4点伤害。',{token:true});
const ga=card('造物甲','将1张『甲』加入手牌。'),gb=card('造物乙','将1张『乙』加入手牌。'),gc=card('造物丙','将1张『丙』加入手牌。');
const two=card('双份','将2张『甲』加入手牌。');
const both=card('两种','将1张『甲』和1张『乙』加入手牌。');
const mode=card('选择','【启动】破坏本卡牌。【模式】选择1个能力发动。\n（1）将1张『甲』加入手牌。\n（2）将1张『丙』加入手牌。\n\n【谢幕曲】抽取1张卡牌。',{type:2});
const deck=[a,b,c,ga,gb,gc,two,both,mode],engine=E.createEngine(deck);
assert.equal(engine.productSimilarity('甲','甲'),1);
assert(engine.productSimilarity('甲','乙')>engine.productSimilarity('甲','丙'));
assert(engine.productSimilarity('甲','乙')<1);
assert(engine.compare(ga,gb).score>engine.compare(ga,gc).score,'Similar generated cards receive more credit than unrelated products');
assert.equal(S.extract(two)[0].numbers[0],'2');assert.equal(S.extract(two)[0].product,'甲');
assert.deepEqual(S.extract(both).map(e=>e.product),['甲','乙']);
assert.deepEqual(E.features(both).get('本体:资源:生成手牌份数').values,[2]);
const branches=E.singleModeTexts(mode.text);assert.equal(branches.length,2);
assert(branches[0].text.includes('破坏本卡牌'));assert(branches[0].text.includes('『甲』'));assert(!branches[0].text.includes('『丙』'));
assert(branches.every(v=>v.text.includes('【谢幕曲】抽取1张卡牌。')));
assert.equal(E.singleModeTexts(mode.text.replace('选择1个','选择2个')).length,0,'Do not model multi-choice as a single branch');
for(const left of deck)for(const right of deck){const x=engine.compare(left,right).score,y=engine.compare(right,left).score;assert(Number.isFinite(x)&&x>=0&&x<=100);assert(Math.abs(x-y)<1e-8);}
const cycleA=card('循环甲','将1张『循环乙』加入手牌。',{token:true}),cycleB=card('循环乙','将1张『循环甲』加入手牌。',{token:true});
const cycleEngine=E.createEngine([cycleA,cycleB]);assert(Number.isFinite(cycleEngine.productSimilarity('循环甲','循环乙')),'Generated card references stop after one level');
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/data.js','utf8'),ctx);
const cards=JSON.parse(JSON.stringify(ctx.window.SVWB_GUESS_DATA.cards)),real=E.createEngine(cards),find=name=>cards.find(c=>c.name===name);
const prayer=find('篡夺的祈祷者'),bastion=find('篡夺的据点'),water=find('纯真的水之妖精'),call=find('妖精召集令');
assert.equal(real.compare(prayer,bastion).modeMatch.right,'模式 1');
assert(real.compare(prayer,bastion).score>35,'The matching golden-product branch should no longer be buried at 27 points');
assert(real.compare(prayer,water).score<50,'Different named products must not receive the old generic 65-point match');
for(const parent of [prayer,bastion,water,call])assert.equal(real.rank(parent,E.poolFor(cards))[0].card.id,parent.id);
console.log('PASS: generated identities/amounts, similar products, mode separation and shared costs, symmetry, recursion bound and real-card regression.');
console.table([bastion,water,call].map(card=>({name:card.name,score:real.compare(prayer,card).score.toFixed(2),...real.compare(prayer,card).modeMatch})));
