const assert=require('node:assert/strict'),fs=require('node:fs'),S=require('./engine');const floor=(t,c)=>t==='超进化时'?6+c*.55:3+c*.5;const counts={midCores:0,crestGrants:0,lateCrests:0,scaledTargets:0,chaos:0},examples={};
const crest={id:'x',deliveryValue:2,effects:[{raw:1}]},grant={kind:'emblem',trigger:'入场曲',condition:'none',ids:['emblemGrant'],emblemIds:['x'],raw:99};assert.equal(S.highCostReadiness({attack:4,health:4,abilities:[grant],emblems:[crest]}),2,'Future emblem investment is not immediate board impact');
for(let i=0;i<10000;i++){const chaos=i>=8000,c=S.generate('收益回归501-'+i,{chaos});if(chaos)counts.chaos++;assert.deepEqual(c,S.generate(c.name,{chaos}));require('./assert-node-effects.cjs')(c);if(c.type==='follower'){assert(c.attack+c.health+c.spent<=c.budget+.011,c.name);assert(c.attack>=0&&c.health>=1);if(c.abilities.some(a=>a.ids.includes('疾驰'))&&c.cost>=5)assert(S.stormCardValue(c.attack,c.health,c.abilities).value<=c.cost*(chaos?1.15:1)+.011,c.name+' storm');}else assert(c.spent<=c.budget+.011,c.name);
for(const a of c.abilities){if(a.midEvolutionCore){counts.midCores++;assert(c.cost>=3&&c.cost<=6);assert(['进化时','超进化时'].includes(a.trigger));assert(a.raw>=floor(a.trigger,c.cost));assert(!c.abilities.some(b=>b.ids.includes('selfEvolve')||b.ids.includes('selfSuperEvolve')));examples.mid??=c.name;}
if(a.targetCount){counts.scaledTargets++;assert.equal(a.targetCount,2);assert.equal(a.trigger,'超进化时');assert(a.text.includes('2个随从'));assert(a.raw>=5.4);examples.targets??=c.name;}
if(c.type==='follower'&&a.ids.includes('emblemGrant'))for(const id of a.emblemIds){const e=c.emblems.find(e=>e.id===id);assert(e);counts.crestGrants++;if(c.cost>=7){counts.lateCrests++;assert(e.usableValue>=5+(c.cost-7)*.5);examples.crest??=c.name;}if(c.cost>=3&&['进化时','超进化时'].includes(a.trigger))assert(e.usableValue>=floor(a.trigger,c.cost));if(['start','end'].includes(e.eventId)&&!e.oneShot)assert.equal(e.limit,null);}
if(a.kind==='core'&&['进化时','超进化时'].includes(a.trigger)&&c.cost>=7)assert(a.raw>=floor(a.trigger,c.cost),c.name+' weak core');}
}
for(const key of ['midCores','crestGrants','lateCrests','scaledTargets'])assert(counts[key]>0,key);fs.writeFileSync(__dirname+'/tempo-validation-501.json',JSON.stringify({version:S.VERSION,samples:10000,counts,examples},null,2));console.log('PASS',counts,examples);
