'use strict';
const assert=require('node:assert/strict'),E=require('./engine.js'),D=require('./data.js'),AI=require('./ai.js');
let groups=0;
function test(name,fn){fn();groups++;console.log('PASS '+name);}
function game(tribe='forest',seed=17171,difficulty='normal',route=0){const s=E.create(tribe,seed,difficulty),o=s.opponents[0];o.hero=tribe;o.name=D.heroes.find(h=>h.id===tribe).name;o.armor=D.heroes.find(h=>h.id===tribe).armor;o.route=route;return {s,o};}
function advance(s,o,to,from=1){for(let r=from;r<=to;r++){s.round=r;o.hp=40;AI.prepare(s,o,E);}}
test('AI uses exported recruitment lifecycle and all sixteen route plans',()=>{assert.equal(typeof E.startRound,'function');assert.equal(typeof E.endRecruit,'function');for(const tribe of D.tribeIds){assert.equal(AI.plans[tribe].length,2);for(const plan of AI.plans[tribe]){assert(plan.length>=5);for(const id of plan)assert(D.cards.some(c=>c.id===id));}}});
test('recruitment is deterministic and leaves the player formation and resources alone',()=>{const x=game('artifact',91283),y=game('artifact',91283);x.s.board=[E.make(x.s,'artifact0')];y.s.board=[E.make(y.s,'artifact0')];const before=JSON.stringify({board:x.s.board,hand:x.s.hand,shop:x.s.shop,hp:x.s.hp,gold:x.s.gold,played:x.s.played,spells:x.s.spells,trinkets:x.s.trinkets});AI.prepare(x.s,x.o,E);AI.prepare(y.s,y.o,E);assert.deepEqual(x.s,y.s);assert.equal(JSON.stringify({board:x.s.board,hand:x.s.hand,shop:x.s.shop,hp:x.s.hp,gold:x.s.gold,played:x.s.played,spells:x.s.spells,trinkets:x.s.trinkets}),before);assert(x.s.uid>0);});
test('all difficulties share the same opening economy and gain no hidden stats',()=>{for(const difficulty of ['easy','normal','hard']){const {s,o}=game('royal',30033,difficulty);AI.prepare(s,o,E);assert.equal(o.aiSummary.budget,3);assert.equal(o.aiSummary.bonusGold,0);assert.equal(o.aiSummary.cardsBought,1);assert.equal(o.board.length,1);assert.equal(o.board[0].golden,false);const d=D.byId[o.board[0].id];assert.equal(o.board[0].attack,d.attack);assert.equal(o.board[0].health,d.health);assert.equal(o.tier,1);}});
test('only the declared late economy bonus depends on difficulty',()=>{for(const [difficulty,bonus]of [['easy',0],['normal',2],['hard',4]]){const {s,o}=game('dragon',101,difficulty);s.round=7;AI.prepare(s,o,E);assert.equal(o.aiSummary.budget,9+bonus);assert.equal(o.aiSummary.bonusGold,bonus);assert(o.aiSummary.goldSpent>=0);assert(o.aiSummary.goldLeft>=0);}});
test('generated end-of-turn spells persist and are really played next round',()=>{const {s,o}=game('rune',8923);o.board=['rune3','rune5','rune6','rune0','rune2','rune4'].map(id=>E.make(s,id));o.tier=5;s.round=10;AI.prepare(s,o,E);const gifts=o.hand.filter(c=>c.id==='mana').map(c=>c.uid);assert(gifts.length>0);const spells=o.spells;s.round=11;AI.prepare(s,o,E);assert(o.spells>spells);assert(gifts.every(uid=>!o.hand.some(c=>c.uid===uid)));assert(o.aiSummary.spellsCast>=3);assert(o.played>=o.aiSummary.spellsCast);});
test('module production, persistent progress without trinket milestones survive turns',()=>{const {s,o}=game('artifact',8001);o.progress={fairy:17,arms:0,prayers:0};o.board=['artifact3','artifact2','artifact6'].map(id=>E.make(s,id));advance(s,o,8);assert.equal(o.progress.fairy,17);assert(o.spells>8);assert(o.progress.arms>0);assert.equal(o.trinkets.length,0);assert(o.hand.some(c=>c.id==='module'));});
test('a heavily grown carry is retained instead of blindly replaced by a higher tier',()=>{const {s,o}=game('dragon',11199);o.board=[E.make(s,'dragon2',{attack:1000,health:1000}),...['dragon3','dragon4','dragon5','dragon0','royal0','forest0'].map(id=>E.make(s,id))];o.tier=6;s.round=13;AI.prepare(s,o,E);assert(o.board.some(c=>c.id==='dragon2'&&c.attack>=1000&&c.health>=1000));});
test('triple offers are bought, merged and their discover reward is resolved',()=>{const {s,o}=game('royal',9121);o.board=[E.make(s,'royal0'),E.make(s,'royal0'),E.make(s,'royal2')];o.shop=[E.make(s,'royal0'),E.make(s,'mana'),E.make(s,'bell')];o.frozen=true;o.tier=2;s.round=3;AI.prepare(s,o,E);assert(o.board.some(c=>c.id==='royal0'&&c.golden)||o.hand.some(c=>c.id==='royal0'&&c.golden));assert(o.aiSummary.triples>=1);assert(o.aiSummary.bought.includes('royal0'));});
test('low-health blood AI reserves life for mandatory triggers instead of chaining optional self-harm',()=>{const {s,o}=game('blood',129);o.hp=8;o.gold=0;o.board=['blood1','blood1'].map(id=>E.make(s,id));o.hand=['bloodPact','blood0','blood3'].map(id=>E.make(s,id));o.amulets=[{...E.make(s,'bloodGarden'),count:1}];s.round=3;AI.prepare(s,o,E,{started:true,bonusGold:false});assert.equal(o.hp,6);assert.equal(o.spells,1);assert.equal(o.bloodDamage,2);assert.equal(o.amulets.length,0);assert(!o.hand.some(c=>c.id==='bloodPact'));});
test('low-health AI can deploy the reworked bat summoner without inventing a self-damage cost',()=>{const {s,o}=game('blood',382);s.round=3;o.hp=3;o.gold=0;o.shop=[];o.hand=[E.make(s,'blood2')];AI.prepare(s,o,E,{started:true,bonusGold:false,deferEnd:true});assert(o.board.some(c=>c.id==='blood2'));assert.equal(o.hp,3);assert.equal(o.bloodDamage,0);});
test('grave spending values the full ritual payload while reserving revival costs',()=>{for(const revival of [false,true]){const {s,o}=game('night',914);const carry=E.make(s,'night5');o.board=revival?[carry,E.make(s,'night7'),E.make(s,'night2')]:[carry];o.hand=[E.make(s,'ritual')];o.grave=revival?12:50;o.gold=0;o.shop=[];s.round=3;const attack=carry.attack;AI.prepare(s,o,E,{started:true,bonusGold:false,deferEnd:true});if(revival){assert.equal(o.grave,12);assert(o.hand.some(c=>c.id==='ritual'));}else{assert.equal(o.grave,0);assert.equal(carry.attack,attack+50);assert.equal(o.spells,1);}}});
test('legacy opponents receive no equipment and pending minion discoveries survive migration',()=>{const {s,o}=game('royal',9811);s.round=10;o.discover=[{type:'minion',title:'三连奖励',text:'选择随从',options:['royal5','royal6','royal7']}];AI.prepare(s,o,E);assert.equal(o.trinkets.length,0);assert(o.stats.triples>=1);s.round=11;AI.prepare(s,o,E);assert.equal(o.trinkets.length,0);});
test('an established fairy army makes summon and opening engines worth replacing large vanilla bodies',()=>{const results=[];for(const strength of [0,80]){const {s,o}=game('forest',99,'normal',1);o.board=['forest6','forest0'].map(id=>E.make(s,id));for(let i=0;i<5;i++)o.board.push(E.make(s,'neutral'+i,{attack:80,health:80}));o.hand=['forest5','forest7'].map(id=>E.make(s,id));o.progress={fairy:strength,arms:0,prayers:0};o.gold=0;o.shop=[];o.tier=6;o.trinkets=['purse','worldtree'];s.round=16;AI.prepare(s,o,E,{started:true,bonusGold:false,deferEnd:true});results.push(o);}assert(!results[0].board.some(c=>c.id==='forest5'));for(const id of ['forest5','forest6','forest7'])assert(results[1].board.some(c=>c.id===id),id+' must remain in the summon engine');});
test('forest combo opens a fuel slot without selling its existing growth and cleave engines',()=>{const {s,o}=game('forest',29);o.board=['forest1','forest4','forest2','forest3','forest7'].map(id=>E.make(s,id));o.board.push(E.make(s,'neutral0',{attack:10,health:10}),E.make(s,'neutral1',{attack:8,health:8}));o.hand=[E.make(s,'fairy'),E.make(s,'forest12'),E.make(s,'bones')];o.progress={fairy:40,arms:0,prayers:0};o.gold=0;o.shop=[];o.tier=6;o.trinkets=['purse','worldtree'];s.round=16;AI.prepare(s,o,E,{started:true,bonusGold:false,deferEnd:true});assert(o.played>=3);assert(o.progress.fairy>40);for(const id of ['forest1','forest4','forest3','forest7'])assert(o.board.some(c=>c.id===id),id+' was incorrectly sold for fuel');});
test('late decisions respect the four-tribe pool, form coherent boards, and converge in bounded operations',()=>{const summary=[];for(const tribe of D.tribeIds)for(let route=0;route<2;route++){const rows=[];for(let seed=1;seed<=6;seed++){const {s,o}=game(tribe,seed*17171,'normal',route);advance(s,o,16);for(const c of o.shop)assert(E.available(s,D.byId[c.id]),c.id);const explicitGifts=new Set(D.cards.filter(c=>E.available(s,c)).flatMap(c=>(c.related||[]).map(r=>r.id).filter(Boolean)));for(const c of [...o.board,...o.hand,...o.amulets])assert(E.available(s,D.byId[c.id])||explicitGifts.has(c.id),c.id);assert(o.board.length<=7&&o.hand.length<=10&&o.amulets.length<=2);assert.equal(o.tier,6);assert.equal(o.route,route);assert.equal(o.aiSummary.routeName,D.archetypes[tribe].routes[route][0]);assert(o.aiSummary.actions<10000);assert(o.aiSummary.spellsCast<=o.played);assert.equal(new Set(o.board.map(c=>c.uid)).size,o.board.length);rows.push({core:o.aiSummary.coreCount,golden:o.board.filter(c=>c.golden).length,spells:o.spells,power:o.aiSummary.boardPower});}const avg=k=>+(rows.reduce((n,r)=>n+r[k],0)/rows.length).toFixed(1);summary.push({tribe,route,cores:avg('core'),golden:avg('golden'),spells:avg('spells'),power:avg('power')});assert(avg('core')>=3,tribe+' route '+route+' lacks a strategy');}console.log(JSON.stringify(summary));});
test('48 complete games with equal, legal recruitment budgets include a player victory',()=>{
 const keys=['board','hand','shop','amulets','trinkets','discover','tier','discount','grave','spells','spellsThisRound','bloodDamage','scrap','progress','stats','hp','armor','pendingGold','pendingFairies','heroCry','constructIndex','frozen','gold','played','powerUsed'],results=[];
 for(const hero of D.tribeIds)for(let route=0;route<2;route++)for(let seed=1;seed<=3;seed++){
  const s=E.create(hero,seed*27919+route*113,'easy');let loops=0;
  while(s.phase!=='finished'&&loops++<45){
   if(s.phase==='recruit'){
    // Reuse the player's actual shop, budget and pending rewards. The public fight
    // action performs endRecruit exactly once; no test creates cards or grants stats.
    const p={...s,tribe:s.hero,route};AI.prepare(s,p,E,{started:true,deferEnd:true,bonusGold:false});for(const k of keys)s[k]=p[k];
    assert.equal(p.aiSummary.bonusGold,0);assert(p.aiSummary.refreshes<=(s.round<7?2:3));assert.equal(E.act(s,'fight').ok,true);
   }
   assert(E.validate(s),hero+' route '+route+' seed '+seed+' round '+s.round);
   if(s.phase==='result')assert.equal(E.act(s,'continue').ok,true);
  }
  assert.equal(s.phase,'finished');results.push({hero,route,rank:s.rank,round:s.round});
 }
 const wins=results.filter(r=>r.rank===1).length;assert(wins>0,'an equal-budget strategic player must be able to win');
 console.log(JSON.stringify({fairGames:results.length,wins,averageRank:+(results.reduce((n,r)=>n+r.rank,0)/results.length).toFixed(2),maxRound:Math.max(...results.map(r=>r.round))}));
});
console.log('\n'+groups+' AI test groups passed.');
