'use strict';
const A=require('node:assert/strict'),fs=require('node:fs'),E=require('./engine'),D=require('./data'),AI=require('./ai');let n=0;function test(label,f){f();console.log('PASS '+label);n++;}
function fresh(){const s=E.create('angel',80341,'hard',['rune','forest','royal','night']);s.tier=5;s.gold=10;s.board=[];s.hand=[];s.shop=[];return s;}
function play(s,id,extra={}){const c=E.make(s,id,extra);s.hand.push(c);const r=E.act(s,'play',{uid:c.uid});A(r.ok,r.message);return c;}
test('sweet supplies ordinary Growth; alchemist is tier 4 with shield',()=>{const s=fresh();s.board=[E.make(s,'rune14')];E.endRecruit(s);A.deepEqual(s.hand.map(c=>c.id),['growth','growth']);A.equal(D.byId.growth.buffRepeats,undefined);A(!D.spells.some(c=>c.id==='doubleGrowth'));A(!D.tokens.some(c=>c.id==='doubleGrowth'));const t=fresh();t.board=[E.make(t,'rune3')];E.endRecruit(t);A.deepEqual(t.hand.map(c=>c.id),['mana','mana','mana']);});
test('every resolution scales with spellcraft, two buffs and two casts per supply',()=>{for(const amp of [0,5,20]){const s=fresh(),target=E.make(s,'neutral0');s.board=[E.make(s,'rune14'),target];s.progress.spellcraft=amp;E.endRecruit(s);s.round++;E.startRound(s);const a=target.attack,h=target.health,b=s.progress.buffs;for(const c of [...s.hand])A(E.act(s,'play',{uid:c.uid,target:target.uid}).ok);A.equal(target.attack-a,2*(2+amp));A.equal(target.health-h,2*(2+amp));A.equal(s.spells,2);A.equal(s.progress.buffs-b,2);A.match(E.scaling.spellView(s,D.byId.doubleGrowth).short,new RegExp('\\+'+(amp+2)+'/\\+'+(amp+2)+' ×2'));}});
test('golden sweet plus neutral end echo gives eight cards',()=>{const s=fresh();s.board=[E.make(s,'rune14',{golden:true}),E.make(s,'neutral16')];E.endRecruit(s);A.equal(s.hand.length,8);A(s.hand.every(c=>c.id==='growth'));});
test('Merlin spreads the complete double-resolution buff',()=>{const s=fresh(),target=E.make(s,'neutral0'),merlin=E.make(s,'rune5'),c=E.make(s,'doubleGrowth');s.board=[merlin,target];s.hand=[c];s.progress.spellcraft=5;const a=merlin.attack;A(E.act(s,'play',{uid:c.uid,target:target.uid}).ok);A.equal(merlin.attack-a,14);A.equal(s.spells,1);});
test('researcher discovers distinct 4-6 star shop spells even below six-star tavern',()=>{for(const tier of [1,5,6]){const s=fresh();s.tier=tier;play(s,'rune20');const q=s.discover[0];A.equal(q.type,'spell');A.equal(q.options.length,3);A.equal(new Set(q.options).size,3);A(q.options.every(id=>D.byId[id].type==='spell'&&D.byId[id].tier>=4&&D.byId[id].tier<=6&&!D.byId[id].token));A(D.discoveryPool(s,D.byId.rune20).some(d=>d.id==='grandBlessing'));const id=q.options[0];A(E.act(s,'choose',{id}).ok);A(s.hand.some(c=>c.id===id));A.equal(s.spells,0);A.equal(s.stats.triples,0);}});
test('golden researcher and fanfare echo queue four save-compatible discoveries',()=>{const s=fresh();s.board=[E.make(s,'neutral14')];play(s,'rune20',{golden:true});A.equal(s.discover.length,4);const saved=JSON.parse(JSON.stringify(s));A(E.validate(saved));E.normalize(saved);while(saved.discover.length)A(E.act(saved,'choose',{id:saved.discover[0].options[0]}).ok);A.equal(saved.hand.length,4);A.equal(saved.stats.triples,0);});
test('full hand pauses spell discovery; invalid foreign or low-tier rewards rejected',()=>{const s=fresh();s.hand=Array.from({length:9},()=>E.make(s,'coin'));play(s,'rune20',{golden:true});A(E.act(s,'choose',{id:s.discover[0].options[0]}).ok);A.equal(s.hand.length,10);A(!E.act(s,'choose',{id:s.discover[0].options[0]}).ok);A.equal(s.discover.length,1);A(E.act(s,'discard',{uid:s.hand[0].uid}).ok);A(E.act(s,'choose',{id:s.discover[0].options[0]}).ok);for(const id of ['mana','rune6','doubleGrowth']){const t=fresh();play(t,'rune20');t.discover[0].options[0]=id;A(!E.validate(t));}});
test('researcher appears in legal tribe and fanfare pools; verified source art exists',()=>{const s=fresh();A(D.discoveryPool(s,D.byId.seekCry).some(c=>c.id==='rune20'));A(E.available(s,D.byId.rune20));s.activeTribes=['forest','royal','night','dragon'];A(!E.available(s,D.byId.rune20));A(fs.existsSync(D.byId.rune20.art));A.equal(D.byId.rune20.sourceName,'禁忌的研究者');});
test('static AI values understand double buffs and researcher without simulating matches',()=>{const s=fresh();s.tribe='rune';s.route=1;s.board=[E.make(s,'neutral0')];A(AI.spellValue(s,D.byId.doubleGrowth)>AI.spellValue(s,D.byId.growth));A(Number.isFinite(AI.synergyValue(s,E.make(s,'rune20'))));});
console.log(n+' arcana groups passed; no AI games.');
