'use strict';
const {chromium}=require('playwright');const path=require('node:path');const fs=require('node:fs');const assert=require('node:assert/strict');const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'qa');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:1080}}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const external=[];page.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});
 await page.goto(pathToFileURL(path.join(root,'sv_tavern.html')).href);await page.getByRole('heading',{name:'选择英雄'}).waitFor();await page.screenshot({path:path.join(out,'01-welcome.png')});
 await page.locator('[data-action="start"]').click();await page.locator('[data-area="shop"]').first().click();await page.locator('.details [data-action="buy"]').click();await page.locator('.details [data-action="play"]').click();assert.equal(await page.locator('.board-row [data-card]').count(),1);
 await page.screenshot({path:path.join(out,'02-first-round.png')});
 await page.locator('[data-action="fight"]').click();await page.locator('[data-action="skip"]').click();await page.locator('[data-action="continue"]').click();assert.equal(await page.evaluate(()=>TavernUI.getState().round),2);
 const uid=await page.locator('[data-area="shop"]').first().getAttribute('data-card');await page.locator('[data-area="shop"]').first().dblclick({delay:90});assert((await page.evaluate(()=>TavernUI.getState().hand)).some(c=>c.uid===+uid));await page.locator(`[data-area="hand"][data-card="${uid}"]`).dblclick({delay:90});assert.equal(await page.evaluate(()=>TavernUI.getState().board.length),2);
 await page.reload();await page.locator('[data-action="resume"]').click();assert.equal(await page.evaluate(()=>TavernUI.getState().round),2);assert.equal(await page.evaluate(()=>TavernUI.getState().board.length),2);
 await page.locator('[data-action="rules"]').click();assert(await page.getByRole('heading',{name:'游戏规则'}).isVisible());await page.locator('[data-action="close"]').click();await page.locator('[data-action="catalog"]').click();await page.locator('[data-action="filter"][data-id="spell"]').click();assert.equal(await page.locator('.catalog-entry').count(),12);await page.locator('[data-action="close"]').click();
 // A representative midgame save exercises populated rows, targeting, amulets and trinkets.
 const fixture=await page.evaluate(()=>{const E=TavernEngine,s=E.create('rune',98412);s.round=8;s.gold=10;s.evo=2;s.tier=4;s.grave=12;s.spells=8;s.trinkets=['quill','mirror'];s.board=['rune0','rune3','rune5','rune6','haven2','forest3','royal5'].map(id=>E.make(s,id));s.board[0].attack=12;s.board[0].health=13;s.board[0].evolved=true;s.board[1].golden=true;s.hand=['growth','clock','shield','rune4','dragon4'].map(id=>E.make(s,id));s.amulets=[{...E.make(s,'garden'),count:1},{...E.make(s,'library'),count:2}];s.shop=['rune5','night5','haven5','royal5','dragon5','team','temple'].map(id=>E.make(s,id));s.opponents.forEach(o=>E.aiPrepare(s,o));return s;});
 await page.addInitScript(s=>localStorage.setItem('duskbound-tavern-save-v1',JSON.stringify(s)),fixture);
 await page.reload();await page.locator('[data-action="resume"]').click();await page.locator('[data-area="shop"]').first().click();await page.screenshot({path:path.join(out,'03-midgame-desktop.png')});
 const spellUid=await page.evaluate(()=>TavernUI.getState().hand.find(c=>c.id==='growth').uid),targetUid=await page.evaluate(()=>TavernUI.getState().board[0].uid);await page.locator(`[data-area="hand"][data-card="${spellUid}"]`).click();await page.locator('.details [data-action="play"]').click();await page.locator(`[data-area="board"][data-card="${targetUid}"]`).click();assert.equal(await page.evaluate(()=>TavernUI.getState().spells),9);
 await page.locator('[data-area="board"]').first().click();await page.locator('.details [data-action="right"]').click();assert.equal(await page.evaluate(()=>TavernUI.getState().board[1].uid),targetUid);
 await page.locator('[data-action="fight"]').click();await page.locator('[data-action="pause"]').click();await page.screenshot({path:path.join(out,'04-battle-desktop.png')});await page.locator('[data-action="skip"]').click();await page.locator('[data-action="continue"]').click();
 // Small screens must expose the inspector without overflow, and allow normal actions.
 await page.setViewportSize({width:390,height:844});await page.locator('[data-area="shop"]').first().click();await page.screenshot({path:path.join(out,'05-mobile.png'),fullPage:true});assert(await page.locator('.mobile-inspect').isVisible());assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile has horizontal overflow');
 await page.locator('[data-action="clear-select"]').click();await page.locator('[data-action="rules"]').click();await page.locator('[data-action="close"]').click();
 // Import a real reward state through the user-facing JSON import, then exercise the hero target flow.
 const E=require('./engine.js'),reward=E.create('royal',94712);reward.gold=10;reward.round=4;reward.board=[E.make(reward,'royal0')];reward.discover=[{type:'minion',title:'三连奖励',text:'选择一名随从',options:['royal0','royal1','royal2']}];
 async function importSave(s){await page.locator('[data-action="menu"]').click();await page.locator('#save-file').setInputFiles({name:'save.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(s))});}
 await importSave(reward);await page.locator('[data-action="choose"][data-id="royal1"]').click();assert.equal(await page.evaluate(()=>TavernUI.getState().hand[0].id),'royal1');await page.locator('[data-action="power"]').click();await page.locator('[data-area="board"]').first().click();assert.equal(await page.locator('.target-banner').count(),0);assert.equal(await page.evaluate(()=>TavernUI.getState().board[0].attack),3);
 const full=E.create('forest',57261);for(let i=0;i<10;i++)full.hand.push(E.make(full,'mana'));for(let i=0;i<3;i++)full.board.push(E.make(full,'royal0'));E.triples(full);await importSave(full);await page.locator('[data-action="discard-reward"]').first().click();await page.locator('[data-action="choose"]').first().click();assert.equal(await page.evaluate(()=>TavernUI.getState().discover.length),0);assert.equal(await page.evaluate(()=>TavernUI.getState().hand.length),10);
 const winner=E.create('dragon',81236);winner.board=[E.make(winner,'dragon7',{attack:999,health:999})];winner.opponents.forEach(o=>o.hp=0);winner.opponents[0].hp=1;winner.opponents[0].armor=0;winner.opponent=0;E.act(winner,'fight');assert.equal(winner.rank,1);await importSave(winner);await page.locator('[data-action="continue"]').click();await page.getByRole('heading',{name:'获得冠军'}).waitFor();await page.screenshot({path:path.join(out,'06-victory-mobile.png'),fullPage:true});await page.locator('[data-action="new"]').click();await page.locator('[data-action="start"]').click();assert.equal(await page.evaluate(()=>TavernUI.getState().round),1);
 const imageFailures=await page.locator('img').evaluateAll(images=>images.filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.alt));assert.deepEqual(imageFailures,[]);assert.deepEqual(external,[],'standalone must make zero network requests');assert.deepEqual(errors,[],'browser console exceptions');
 console.log('PASS browser: real purchases/deployment, double click, round progression, reload/continue, rules, catalog, targeted spells, formation, replay, mobile inspector, zero broken images, zero network requests, zero JS errors.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
