'use strict';
const fs=require('node:fs');const path=require('node:path');const D=require('./data.js');
const root=path.resolve(__dirname,'..');
const paths=[...new Set([...D.cards,...(D.retiredCards||[]),...D.spells,...D.retiredSpells,...D.amulets,...D.tokens,...D.heroes,...D.trinkets].map(c=>c.art))];
const assets={};for(const p of paths){const full=path.join(root,p);if(!fs.existsSync(full))throw Error('Missing art: '+p);assets[p]='data:image/'+(p.endsWith('.webp')?'webp':'png')+';base64,'+fs.readFileSync(full).toString('base64');}
let html=fs.readFileSync(path.join(__dirname,'shell.html'),'utf8');
const replacements={STYLE:fs.readFileSync(path.join(__dirname,'style.css'),'utf8'),ASSETS:'window.TAVERN_ASSETS='+JSON.stringify(assets)+';',IDENTITY:fs.readFileSync(path.join(__dirname,'identity.js'),'utf8'),DATA:fs.readFileSync(path.join(__dirname,'data.js'),'utf8'),ENGINE:fs.readFileSync(path.join(__dirname,'engine.js'),'utf8'),APP:fs.readFileSync(path.join(__dirname,'app.js'),'utf8')};
replacements.EXPANSION=fs.readFileSync(path.join(__dirname,'expansion.js'),'utf8');replacements.EFFECTS=fs.readFileSync(path.join(__dirname,'effects.js'),'utf8');replacements.COMBAT=fs.readFileSync(path.join(__dirname,'combat.js'),'utf8');
for(const tag of ['SCALING','BALANCE','DIVERSITY','SYNERGIES','HEROES','TUNING','ARCHETYPES','CONSTRUCTS','ROYAL','MARKET','INJURY','UTILITY','NECROMANCY','FUNCTIONAL','AMULET-EXPANSION','DECISIONS','VITALITY','RESONANCE','BARRIERS','DISTINCTIVE','NEUTRAL-ECHOES','NEUTRAL-SPELLS','COMMERCE','ASCENSION','LEADER-PORTRAITS','ARCANA','REINFORCEMENTS','EXPEDITION','REFORGED','RENEWAL','AI','ECHOES','ANIMATIONS'])replacements[tag]=fs.readFileSync(path.join(__dirname,tag.toLowerCase()+'.js'),'utf8');
const voices=JSON.parse(fs.readFileSync(path.join(__dirname,'assets/voices/manifest.json'),'utf8')),voiceAssets={};
for(const entry of Object.values(voices.cards))for(const kind of ['play','attack','death'])if(entry[kind]&&!voiceAssets[entry[kind]])voiceAssets[entry[kind]]='data:audio/mpeg;base64,'+fs.readFileSync(path.join(__dirname,'assets/voices',entry[kind])).toString('base64');
replacements.VOICES='window.TAVERN_VOICES='+JSON.stringify({cards:voices.cards,assets:voiceAssets})+';\n'+fs.readFileSync(path.join(__dirname,'voices.js'),'utf8');
replacements.STYLE+='\n'+fs.readFileSync(path.join(__dirname,'selfplay.css'),'utf8');
replacements.SELFPLAY=fs.readFileSync(path.join(__dirname,'selfplay.js'),'utf8');
const workerTags=[...html.matchAll(/\/\*__([A-Z-]+)__\*\//g)].map(m=>m[1]).filter(tag=>!['STYLE','ASSETS','APP','VOICES','ECHOES','ANIMATIONS','SELFPLAY','SELFPLAY-UI'].includes(tag));
const workerSource=workerTags.map(tag=>replacements[tag]).join('\n')+'\n'+replacements.SELFPLAY+'\n'+fs.readFileSync(path.join(__dirname,'selfplay-worker.js'),'utf8');
const samplesPath=path.join(__dirname,'qa/selfplay-results.json'),samples=fs.existsSync(samplesPath)?JSON.parse(fs.readFileSync(samplesPath,'utf8')).reports.filter(r=>r.version===D.rulesVersion):[];
replacements['SELFPLAY-UI']='window.TAVERN_SELFPLAY_SAMPLES='+JSON.stringify(samples).replace(/<\/script/gi,'<\\/script')+';\nwindow.TAVERN_SELFPLAY_WORKER='+JSON.stringify(workerSource).replace(/<\/script/gi,'<\\/script')+';\n'+fs.readFileSync(path.join(__dirname,'selfplay-ui.js'),'utf8');
for(const [tag,body] of Object.entries(replacements))html=html.replace(`/*__${tag}__*/`,()=>body);
const output=path.join(root,'sv_tavern.html');const pending=output+'.building';fs.writeFileSync(pending,html);fs.renameSync(pending,output);console.log('Built '+output+' ('+(Buffer.byteLength(html)/1024/1024).toFixed(2)+' MiB, '+paths.length+' embedded illustrations, '+Object.keys(voiceAssets).length+' voices)');
