'use strict';
const {chromium}=require('playwright'),{pathToFileURL}=require('node:url'),path=require('node:path'),assert=require('node:assert/strict'),fs=require('node:fs');const E=require('./engine.js'),D=require('./data.js');
const url=pathToFileURL(path.resolve(__dirname,'../sv_tavern.html')).href;
function state(){const s=E.create('forest',888);s.gold=20;s.tier=4;s.board=['royal0','night5'].map(id=>E.make(s,id));s.hand=['growth','garden','dragon0','clock'].map(id=>E.make(s,id));s.shop=['forest0','forest2','night5','rune1','growth','egg'].map(id=>E.make(s,id));return s;}
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1080}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await context.addInitScript(s=>localStorage.setItem('duskbound-tavern-save-v1',JSON.stringify(s)),state());await page.goto(url);await page.locator('[data-action="resume"]').click();
 const get=()=>page.evaluate(()=>TavernUI.getState());const card=(area,uid)=>page.locator(`[data-area="${area}"][data-card="${uid}"]`);async function drag(source,target,options){await source.dragTo(target,options);await page.waitForTimeout(430);}
 let s=await get(),bought=s.shop[0].uid;await drag(card('shop',bought),page.locator('[data-drop="hand"]'));s=await get();assert.equal(s.gold,17);assert(s.hand.some(c=>c.uid===bought));
 await drag(card('hand',bought),card('board',s.board[0].uid),{targetPosition:{x:5,y:60}});s=await get();assert.equal(s.board[0].uid,bought);assert.equal(s.board.length,3);
 const direct=s.shop[0].uid;await drag(card('shop',direct),page.locator('.board-row .empty-slot').first());s=await get();assert(s.board.some(c=>c.uid===direct));assert.equal(s.gold,14);assert(s.hand.some(c=>c.id==='growth'),'fanfare generated real spell');
 const target=s.board[0],spell=s.hand.find(c=>c.id==='growth');await drag(card('hand',spell.uid),card('board',target.uid));s=await get();assert.equal(s.board[0].attack,target.attack+3);assert(!s.hand.some(c=>c.uid===spell.uid));
 const a=s.hand.find(c=>c.id==='garden');await drag(card('hand',a.uid),page.locator('[data-drop="amulet"]'));s=await get();assert.equal(s.amulets[0].id,'garden');
 const mover=s.board.at(-1);await drag(card('board',mover.uid),card('board',s.board[0].uid),{targetPosition:{x:3,y:60}});s=await get();assert.equal(s.board[0].uid,mover.uid);
 const beforeGold=s.gold;await drag(card('board',mover.uid),page.locator('[data-drop="shop"]'));s=await get();assert.equal(s.gold,beforeGold+1);assert(!s.board.some(c=>c.uid===mover.uid));
 const before=JSON.stringify(s);await drag(card('shop',s.shop[0].uid),page.locator('.brand'));assert.equal(JSON.stringify(await get()),before,'invalid drop must be a no-op');
 const cerb=s.board.find(c=>c.id==='night5');await card('board',cerb.uid).click();await page.locator('.details [data-related-id="hound"]').waitFor();assert((await page.locator('.details [data-related-id="hound"]').innerText()).includes('造成 2 点伤害'));assert((await page.locator('.details [data-related-id="coco"]').innerText()).includes('+2/+2'));await page.screenshot({path:path.join(__dirname,'qa','07-correct-identity-tokens.png')});
 await page.locator('.details [data-action="related"]').click();assert.equal(await page.locator('.modal .related-entry').count(),2);await page.locator('.modal [data-action="close"]').click();await page.locator('[data-action="catalog"]').click();await page.locator('[data-action="filter"][data-id="token"]').click();assert.equal(await page.locator('.catalog-entry').count(),9);await page.locator('[data-action="close"]').click();
 // Actual touch events go through the pointer drag implementation, including invalid and successful drops.
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.addInitScript(s=>localStorage.setItem('duskbound-tavern-save-v1',JSON.stringify(s)),state());const mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto(url);await mp.locator('[data-action="resume"]').click();const cdp=await mobile.newCDPSession(mp);let ms=await mp.evaluate(()=>TavernUI.getState()),mu=ms.shop[0].uid;
 async function touchDrag(source,target){const a=await source.boundingBox(),b=await target.boundingBox(),sx=a.x+a.width/2,sy=a.y+a.height/2,tx=b.x+b.width/2,ty=b.y+b.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:sx,y:sy}]});for(let i=1;i<=14;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:sx+(tx-sx)*i/14,y:sy+(ty-sy)*i/14}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await mp.waitForTimeout(450);}
 await touchDrag(mp.locator(`[data-area="shop"][data-card="${mu}"]`),mp.locator('[data-drop="board"]'));ms=await mp.evaluate(()=>TavernUI.getState());assert(ms.board.some(c=>c.uid===mu),'touch shop-to-board must buy and deploy');assert.equal(ms.gold,17);
 await mp.locator('[data-area="board"]').filter({hasText:'凯尔贝洛斯'}).click();await mp.screenshot({path:path.join(__dirname,'qa','08-mobile-token-inspection.png'),fullPage:true});assert(await mp.locator('.mobile-inspect [data-related-id="coco"]').isVisible());assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);console.log('PASS desktop and real touch drags: buy, direct deploy, ordered placement, targeted spell, amulet, sell, invalid rollback; token effects, identity, token codex, mobile inspector.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
