'use strict';
const A=require('node:assert/strict'),fs=require('fs'),D=require('./data'),E=require('./engine'),AI=require('./ai'),S=E.scaling;let passed=0;
function test(n,f){f();console.log('PASS '+n);passed++;}
function fresh(hero='angel'){const h=D.heroes.find(h=>h.id===hero),ts=h.tribe==='neutral'?['forest','rune','night','artifact']:[h.tribe,...D.tribeIds.filter(t=>t!==h.tribe).slice(0,3)];const s=E.create(hero,24891,'hard',ts);s.board=[];s.hand=[];s.shop=[];s.gold=20;s.tier=6;return s;}
const add=(s,id,x={})=>{const c=E.make(s,id,x);s.board.push(c);return c;};
function act(s,t,a={}){const r=E.act(s,t,a);A(r.ok,r.message);return r;}
function play(s,id,x={},target){const c=E.make(s,id,x);s.hand.push(c);act(s,'play',{uid:c.uid,target});return c;}
const quiet=(s,id)=>E.make(s,id,{attack:0,health:10000,keywords:['stealth','cannotAttack']});
const foe=s=>E.make(s,'neutral0',{attack:100000,health:100000});
test('complete identities, exact class coverage, ten identity-matched dual cards, less crowded four-star pool',()=>{A.equal(D.cards.length,223);for(const t of D.tribeIds){A.equal(D.cards.filter(d=>d.tribe===t).length,['night','haven'].includes(t)?26:t==='rune'?24:25);A.equal(D.cards.filter(d=>d.tribes?.includes(t)).length,({forest:3,royal:2,dragon:3,night:3,rune:4,haven:2,blood:2,artifact:1})[t]);}for(const id of D.expeditionIds){const d=D.byId[id];A.equal(d.name,d.sourceName);A(fs.existsSync(d.art));A(d.goldenText);}A.equal(D.byId.dragon24.name,'培冬');A.equal(D.byId.dragon24.tier,6);A.equal(D.byId.rune3.tier,4);A(D.byId.rune3.keywords.includes('shield'));A.equal(D.byId.rune16.tier,5);A.equal(D.byId.rune14.tier,3);A(!D.byId.rune14.text.includes('两次'));});
test('mining investment does not grant immediate gold and ignores spell amplification',()=>{const s=fresh();s.round=8;s.progress.spellcraft=100;const gold=s.gold;play(s,'mining');A.equal(s.gold,gold);A.equal(s.progress.goldCapBonus,1);A.equal(S.goldCap(s),11);s.round++;E.startRound(s);A.equal(s.gold,11);A(E.validate(s));for(let i=0;i<5;i++)play(s,'mining');A.equal(S.goldCap(s),16);A.equal(s.gold,11);s.round++;E.startRound(s);A.equal(s.gold,16);});
test('amulet raises gold cap directly while hunter rewards spending',()=>{const s=fresh();s.progress.devotion=99;play(s,'mine');add(s,'neutral18');E.endRecruit(s);A.equal(s.progress.goldCapBonus,0);A.equal(s.amulets[0].count,1);s.round++;E.startRound(s);E.endRecruit(s);A.equal(s.progress.goldCapBonus,2);A.equal(S.goldCap(s),12);A.equal(s.gold,4);const t=fresh();add(t,'neutral18',{golden:true});add(t,'neutral16');t.goldSpentThisRound=8;E.endRecruit(t);A.equal(t.hand.filter(c=>c.id==='coin').length,4);});
test('campaign plays count actual casts, minions and amulets, never fanfare repeats or summons',()=>{const s=fresh();s.deferTriples=true;add(s,'neutral14');play(s,'forest8');A.equal(s.progress.totalPlayed,1);A.equal(s.board.filter(c=>c.id==='fairy').length,4);play(s,'coin');play(s,'mine');A.equal(s.progress.totalPlayed,3);s.round++;E.startRound(s);A.equal(s.progress.totalPlayed,3);A.equal(s.played,0);});
test('fairy summon payoffs work in recruitment and combat; no double count on hand play',()=>{const s=fresh(),army=add(s,'forest2'),rally=add(s,'forest16'),left=add(s,'neutral0');play(s,'forest8');A.equal(s.progress.fairy,2);A.equal(left.attack,D.byId.neutral0.attack+4);act(s,'sell',{uid:left.uid});const f=play(s,'fairy');A.equal(s.progress.fairy,3);const r=E.combat(s,[quiet(s,'forest2'),quiet(s,'forest16'),E.make(s,'forest0',{attack:0,health:1,keywords:['taunt']})],[foe(s)]);A.equal(r.progress[0].fairy,1);A(Object.values(r.permanent[0]).some(g=>g.attack===2));A(f);});
test('career opening grows from campaign plays and stays temporary',()=>{const s=fresh(),c=E.make(s,'forest22'),other=quiet(s,'neutral0'),r=E.combat(s,[c,other,quiet(s,'forest23')],[foe(s)],{progress:{totalPlayed:60}});const frame=r.events.find(e=>e.text.includes('开战效果结算完成'));A.equal(frame.boards[0].find(x=>x.uid===c.uid).attack,c.attack+60+60);A.equal(r.permanent[0][c.uid],undefined);A.equal(c.attack,D.byId.forest22.attack);});
test('discarded fuel resolves rewards without triggering Pydon',()=>{const s=fresh(),receiver=add(s,'neutral0');add(s,'dragon24');const c=E.make(s,'dragon22');s.hand=[c];act(s,'discard',{uid:c.uid});A.deepEqual(s.hand.map(c=>c.id),['dragonWing','dragonWing']);A.equal(s.stats.discards,1);A.equal(s.progress.tavernAttack,0);A.equal(receiver.attack,D.byId.neutral0.attack);const d=E.make(s,'dragon23');s.hand.push(d);act(s,'discard',{uid:d.uid});A.equal(s.progress.tavernAttack,4);A.equal(s.stats.discards,2);act(s,'discard',{uid:s.hand[0].uid});A.equal(s.progress.tavernAttack,4);});
test('bone prince low-tier avenge grants permanent 5/5 every three friendly deaths',()=>{const s=fresh(),c=quiet(s,'night22'),team=[...Array.from({length:3},()=>E.make(s,'neutral0',{attack:0,health:1,keywords:['taunt']})),c],r=E.combat(s,team,[foe(s)]);A.equal(r.permanent[0][c.uid].attack,5);A.equal(r.permanent[0][c.uid].health,5);});
test('guard nesting yields two sequential taunts and legion health supports reborn',()=>{const s=fresh(),r=E.combat(s,[E.make(s,'haven22',{attack:0,health:1}),quiet(s,'neutral0')],[foe(s)]);for(const id of ['holyGuardian','holyWisp'])A(r.events.some(e=>e.kind==='summon'&&e.boards[0].some(c=>c.id===id&&c.keywords.includes('taunt'))));const t=fresh(),q=E.combat(t,[E.make(t,'night23',{attack:0,health:1,keywords:['taunt']}),quiet(t,'night24')],[foe(t)],{progress:{legionAttack:10}});A(q.events.some(e=>e.kind==='summon'&&e.boards[0].some(c=>c.id==='skeleton'&&c.health===27&&c.reborn)));});
test('health to attack choice, scaling end and save validation',()=>{const s=fresh(),c=add(s,'neutral0',{attack:2,health:90,keywords:['taunt']});play(s,'haven23');A(E.validate(s));act(s,'choose',{id:String(c.uid)});A.equal(c.attack,90);add(s,'haven24');E.endRecruit(s);A.equal(c.health,120);});
test('chosen feast uses selected offer, repeats independently and removes stale offers',()=>{const s=fresh();add(s,'neutral14');add(s,'blood23');add(s,'blood24');s.shop=[E.make(s,'neutral0',{attack:9,health:12})];const food=s.shop[0],c=play(s,'blood22');A.equal(s.discover.length,2);A(E.validate(s));const hp=s.hp;act(s,'choose',{id:String(food.uid)});A.equal(s.hp,hp-2);A.equal(s.discover.length,0);A.equal(s.shop.length,0);A.equal(s.progress.tavernAttack,2);A.equal(c.attack,3);const receiver=s.board.find(x=>x.uid===s.feasts[0].targets[0]);A.notEqual(receiver.uid,c.uid);A.equal(receiver.attack,D.byId[receiver.id].attack+9);A(E.validate(s));});
test('Baphomet feeds only another ally, golden doubles, solo costs nothing and hero remains independent',()=>{A.equal(D.byId.blood22.tier,2);for(const golden of [false,true]){const s=fresh(),ally=add(s,'neutral0'),a=ally.attack,h=ally.health,food=E.make(s,'neutral1',{attack:7,health:9});s.shop=[food];const c=play(s,'blood22',{golden}),ownAttack=c.attack;A(E.validate(s));act(s,'choose',{id:String(food.uid)});A.equal(ally.attack,a+7*(golden?2:1));A.equal(ally.health,h+9*(golden?2:1));A.equal(c.attack,ownAttack);A.deepEqual(s.feasts[0].targets,[ally.uid]);A.equal(s.hp,38);}const solo=fresh();solo.shop=[E.make(solo,'neutral0')];play(solo,'blood22');A.equal(solo.discover.length,0);A.equal(solo.shop.length,1);A.equal(solo.hp,40);const hero=fresh('medusa'),c=add(hero,'blood22'),food=E.make(hero,'neutral0');hero.shop=[food];act(hero,'power');act(hero,'choose',{id:String(food.uid)});A.equal(c.attack,D.byId.blood22.attack+food.attack);A(E.validate(hero));});
test('construct cache gains random token on fanfare and queues random token on death',()=>{const s=fresh(),c=play(s,'artifact22');A.equal(s.hand.length,1);A(D.constructCycle.includes(s.hand[0].id));const r=E.combat(s,[{...c,attack:0,health:1},quiet(s,'neutral15')],[foe(s)]);A.equal(r.generated[0].length,2);A(r.generated[0].every(id=>D.constructCycle.includes(id)));A.equal(s.hand.length,1);});
test('construct variety tracks once per kind each round; union growth reads kinds times arms',()=>{const s=fresh();add(s,'artifact23');play(s,'analyzer');play(s,'analyzer');A.equal(s.progress.arms,2);play(s,'mysticArtifact');A.equal(s.progress.arms,4);A.deepEqual(s.progress.constructTypes,['analyzer','mysticArtifact']);s.round++;E.startRound(s);act(s,'sell',{uid:s.board.find(c=>c.id==='analyzer').uid});play(s,'analyzer');A.equal(s.progress.arms,6);A(E.validate(s));const t=fresh(),core=quiet(t,'artifact24'),r=E.combat(t,[E.make(t,'artifact1',{attack:0,health:1,keywords:['taunt']}),core],[foe(t)],{progress:{arms:12,constructTypes:['analyzer','mysticArtifact']}});A.equal(r.permanent[0][core.uid].attack,6);});
test('low spell discover and end spell upgrade use active pool; no resource multiplication',()=>{const s=fresh();play(s,'rune22',{golden:true});A.equal(s.discover.length,2);A(E.validate(s));while(s.discover.length)act(s,'choose',{id:s.discover[0].options[0]});add(s,'rune24',{golden:true});E.endRecruit(s);A.equal(s.hand.length,2);A(s.hand.every(c=>D.byId[c.id].tier>=5));});
test('dual species participate in pool, module targeting, royal discovery and military growth',()=>{const s=fresh();s.activeTribes=['forest','rune','blood','haven'];A(E.available(s,D.byId.forest21));A(E.available(s,D.byId.royal16));A(!E.available(s,D.byId.royal4));A(D.discoveryPool(s,D.byId.royal21).some(d=>d.id==='royal16'));const c=add(s,'dragon20'),spell=E.make(s,'module');s.shop=[spell];act(s,'buyPlay',{uid:spell.uid,target:c.uid});A.equal(c.attack,D.byId.dragon20.attack+1);const t=fresh(),d=E.make(t,'royal4'),r=E.combat(t,[d],[foe(t)],{progress:{legionAttack:11}});A.equal(r.events[0].boards[0][0].attack,d.attack+11);});
test('Odin destroys lethal attacker including shields, but not a spell killer',()=>{const s=fresh(),odin=E.make(s,'neutral10',{attack:0,health:2,keywords:['taunt']}),enemy=foe(s);enemy.keywords=['shield'];const r=E.combat(s,[odin],[enemy]);A(r.events.some(e=>e.kind==='destroy'&&e.text.includes('复仇摧毁')));A.equal(r.survivors[1].length,0);const t=fresh(),r2=E.combat(t,[E.make(t,'neutral10')],[E.make(t,'dragon7',{attack:100,health:100})]);A(!r2.events.some(e=>e.text.includes('复仇摧毁')));});
test('one-shot venom works on retaliation, shield preserves charge, full venom also retaliates',()=>{for(const id of ['neutral19','neutral20']){const s=fresh(),r=E.combat(s,[E.make(s,id,{attack:1,health:1,keywords:['taunt',...D.byId[id].keywords]})],[foe(s)]);A.equal(r.survivors[1].length,0);}const s=fresh(),p=E.make(s,'neutral19',{attack:1,health:100,keywords:['taunt']}),r=E.combat(s,[p],[E.make(s,'neutral0',{attack:1,health:1000,keywords:['shield']})]);A(r.events.some(e=>e.kind==='attack'&&e.boards[0].some(c=>c.uid===p.uid&&!c.venomSpent)));A.equal(r.survivors[1].length,0);});
test('Rowen scouting replaces an offer once, resetting if unused',()=>{const s=fresh('dragon');s.tier=2;act(s,'power');act(s,'refresh');A.equal(D.byId[s.shop[0].id].tier,3);A(!s.heroProspect);s.round++;E.startRound(s);A(!s.heroProspect);});
test('Aria bounce returns original bonuses plus base copy; no immediate economic loop',()=>{const s=fresh('aria'),c=add(s,'fairy',{attack:10,health:12});act(s,'power',{target:c.uid});A.equal(s.board.length,0);A.deepEqual(s.hand.map(x=>x.attack),[10,1]);A(!E.act(s,'power',{target:c.uid}).ok);});
test('mercenary sale has star value once and no additive bonus',()=>{const s=fresh('roland'),c=add(s,'neutral5'),d=add(s,'neutral1');act(s,'power');const g=s.gold;act(s,'sell',{uid:c.uid});A.equal(s.gold-g,6);act(s,'sell',{uid:d.uid});A.equal(s.gold-g,7);});
test('Cerberus discovers and hunter copies public opponent cards, respecting tier',()=>{const s=fresh('ceres');s.grave=3;act(s,'power');A.equal(s.grave,0);A(E.validate(s));A(s.discover[0].options.every(id=>D.abilityIds.lastWords.includes(id)));act(s,'choose',{id:s.discover[0].options[0]});const t=fresh('windgod');A(!E.act(t,'power').ok);A.equal(t.gold,20);t.lastOpponent=t.opponents[0].id;t.opponents[0].board=[E.make(t,'neutral0'),E.make(t,'fairy')];act(t,'power');A.deepEqual(t.discover[0].options,['neutral0']);A(E.validate(t));});
test('Medusa selects food; Brodia redistributes real layers and triggers loss',()=>{const s=fresh('medusa'),c=add(s,'neutral0');s.shop=[E.make(s,'neutral1')];act(s,'power');act(s,'choose',{id:s.discover[0].options[0]});A.equal(s.hp,38);A.equal(c.attack,D.byId.neutral0.attack+D.byId.neutral1.attack);const t=fresh('athena'),left=add(t,'neutral0'),center=add(t,'royal0'),right=add(t,'neutral0');const a=center.attack;act(t,'power',{target:center.uid});A.equal(S.shieldCount(center),0);A.equal(S.shieldCount(left),1);A.equal(S.shieldCount(right),1);A.equal(center.attack,a+1);});
test('Oz recasts next spell only; Ion transforms chosen hand minion with bonus preservation',()=>{const s=fresh('olivia');act(s,'power');play(s,'coin');A.equal(s.hand.length,0);A.equal(s.spells,2);A.equal(s.gold,21);play(s,'coin');A.equal(s.spells,3);const t=fresh('bahamut'),d=D.byId.neutral1,c=E.make(t,d.id,{attack:d.attack+10,health:d.health+20});t.hand=[c];act(t,'power');A(E.validate(t));act(t,'choose',{id:String(c.uid)});const x=t.hand[0];A.notEqual(x.id,c.id);A.equal(D.byId[x.id].tier,d.tier);A.equal(x.attack-D.byId[x.id].attack,10);A.equal(x.health-D.byId[x.id].health,20);A(E.validate(t));});
test('new cards have finite static AI scores, formulas and save-compatible values',()=>{const s=fresh();s.tribe='artifact';s.route=1;s.board=[E.make(s,'neutral0')];for(const id of D.expeditionIds){const c=E.make(s,id);A(Number.isFinite(AI.synergyValue(s,c)),id);A(!/NaN|undefined/.test(S.formulaText(s,c,D.byId[id].text)),id);}A(Number.isFinite(AI.spellValue(s,D.byId.mining)));A(Number.isFinite(AI.amuletValue(s,D.byId.mine)));const t=E.copy(s);t.progress.constructTypes=['coin'];A(!E.validate(t));});
test('battle-generated cards settle into hand without mid-combat triples or AI simulation',()=>{const s=fresh(),o=s.opponents.find(o=>o.id===s.opponent);s.opponents.forEach(x=>{if(x!==o)x.hp=0;});s.board=[E.make(s,'artifact22',{attack:0,health:1})];o.board=[foe(s)];global.TavernAI={prepare:()=>{}};try{act(s,'fight');A.equal(s.hand.length,1);A(D.constructCycle.includes(s.hand[0].id));A.equal(s.discover.length,0);A(E.validate(s));A(s.result.events.some(e=>e.text.includes('战后获得')));A(s.log.some(e=>e.includes('战后获得')));}finally{delete global.TavernAI;}});
test('full-hand death rewards are discarded cleanly and do not leak to following turns',()=>{const s=fresh(),o=s.opponents.find(o=>o.id===s.opponent);s.opponents.forEach(x=>{if(x!==o)x.hp=0;});s.hand=Array.from({length:10},()=>E.make(s,'coin'));s.board=[E.make(s,'artifact22',{attack:0,health:1})];o.board=[foe(s)];global.TavernAI={prepare:()=>{}};try{act(s,'fight');A.equal(s.hand.length,10);A(s.hand.every(c=>c.id==='coin'));A(s.log.some(e=>e.includes('手牌已满')));A(E.validate(s));}finally{delete global.TavernAI;}});
test('end feast shares notifications and targeting a taunt gains health and attack',()=>{const s=fresh();add(s,'blood9');add(s,'blood23');s.shop=[E.make(s,'neutral0')];E.endRecruit(s);A.equal(s.progress.tavernAttack,2);const t=fresh(),target=add(t,'neutral0',{attack:2,health:3,keywords:['taunt']});add(t,'rune23');play(t,'growth',{},target.uid);A.equal(target.attack,6);A.equal(target.health,7);});
test('golden target payloads and invalid hero actions keep their proper costs',()=>{const s=fresh(),c=add(s,'neutral0',{attack:5,health:30});play(s,'haven23',{golden:true});act(s,'choose',{id:String(c.uid)});A.equal(c.attack,60);const t=fresh('aria'),x=add(t,'neutral0');A(!E.act(t,'power',{target:x.uid}).ok);A.equal(t.gold,20);A(!t.powerUsed);const u=fresh('medusa');add(u,'neutral0');u.hp=1;u.shop=[E.make(u,'neutral0')];A(!E.act(u,'power').ok);A.equal(u.gold,20);A.equal(u.discover.length,0);});
console.log(passed+' expedition groups passed; no AI matches simulated.');
