'use strict';
const A=require('node:assert/strict'),D=require('./data'),E=require('./engine'),AI=require('./ai'),S=E.scaling;let total=0;
const test=(n,f)=>{f();console.log('PASS '+n);total++;};
function fresh(){const s=E.create('angel',56789,'hard',['haven','royal','night','forest']);s.board=[];s.hand=[];s.shop=[];s.gold=20;s.tier=6;return s;}
const quiet=(s,id,extra={})=>E.make(s,id,{attack:0,health:10000,keywords:['cannotAttack','stealth'],...extra});
const act=(s,t,a={})=>{const r=E.act(s,t,a);A(r.ok,r.message);A(E.validate(s));};
function play(s,id,extra={}){const c=E.make(s,id,extra);s.hand.push(c);act(s,'play',{uid:c.uid});return c;}
test('Olivia restores mass battlecry while singer no longer grants a battlecry spell',()=>{for(const golden of [false,true]){const s=fresh(),c=E.make(s,'neutral0');s.board=[c];const a=c.attack,h=c.health;play(s,'neutral4',{golden});play(s,'neutral12');A.equal(c.attack,a+(golden?12:6));A.equal(c.health,h+(golden?12:6));A.equal(s.hand.length,0);}});
test('fist saint sets both stats to maximum, golden doubles maximum, including attack-heavy targets',()=>{for(const [a,h,gold] of [[30,10,false],[10,30,false],[30,10,true]]){const s=fresh(),c=E.make(s,'neutral0',{attack:a,health:h});s.board=[c];play(s,'haven23',{golden:gold});act(s,'choose',{id:String(c.uid)});A.equal(c.attack,30*(gold?2:1));A.equal(c.health,c.attack);A.equal(D.byId.haven23.tier,6);}});
test('self memory keeps temporary opening stats, golden retains twice, initial board remains untouched',()=>{for(const golden of [false,true]){const s=fresh(),c=quiet(s,'haven8',{golden}),aura=quiet(s,'forest23'),r=E.combat(s,[c,aura],[quiet(s,'neutral0')],{progress:{totalPlayed:10}});A.deepEqual(r.permanent[0][c.uid],{attack:golden?20:10,health:golden?20:10});A.equal(c.attack,0);A.equal(c.health,10000);}});
test('adjacent memory works across tribes and overlapping sources do not duplicate gains',()=>{const s=fresh(),a=quiet(s,'haven20'),c=quiet(s,'haven8'),b=quiet(s,'haven20',{golden:true}),far=quiet(s,'neutral0'),source=quiet(s,'forest23'),r=E.combat(s,[a,c,b,far,source],[quiet(s,'neutral0')],{progress:{totalPlayed:9}});A.deepEqual(r.permanent[0][c.uid],{attack:18,health:18});A.deepEqual(r.permanent[0][far.uid],{attack:18,health:18});A.equal(r.permanent[0][source.uid],undefined);});
test('memory never duplicates permanent growth or retains starting army bonuses',()=>{const s=fresh(),a=quiet(s,'haven20',{golden:true}),c=quiet(s,'dragon2',{dragonPings:1}),r=E.combat(s,[a,c],[quiet(s,'neutral0')]);A.deepEqual(r.permanent[0][c.uid],{attack:D.tuning.dragonHurt,health:D.tuning.dragonHurt});const t=fresh(),x=quiet(t,'night1'),q=E.combat(t,[quiet(t,'haven20'),x],[quiet(t,'neutral0')],{progress:{legionAttack:100}});A.equal(q.permanent[0][x.uid],undefined);});
test('retained gains survive death without saving damage or shielding',()=>{const s=fresh(),c=E.make(s,'haven8',{attack:0,health:1,keywords:['taunt']}),r=E.combat(s,[c,quiet(s,'forest23')],[E.make(s,'neutral0',{attack:100000,health:100000})],{progress:{totalPlayed:8}});A.deepEqual(r.permanent[0][c.uid],{attack:8,health:8});A(r.deadCount[0]>0);});
test('guard nurse works cross-tribe and guard vitals uses one snapshot for every guard',()=>{const s=fresh(),n=E.make(s,'haven12'),other=E.make(s,'neutral0');s.board=[n,other];const h=other.health;play(s,'garden');A(other.keywords.includes('taunt'));A.equal(other.health,h+5);const t=fresh(),a=E.make(t,'neutral0',{health:60,keywords:['taunt']}),b=E.make(t,'neutral1',{health:10,keywords:['taunt']});t.board=[E.make(t,'haven24'),a,b];E.endRecruit(t);A.equal(a.health,80);A.equal(b.health,30);});
test('guard witness strengthens the attacked guard, including foreign tribes',()=>{const s=fresh(),guard=E.make(s,'neutral0',{attack:100,health:10,keywords:['taunt','cannotAttack']}),source=quiet(s,'haven3',{health:8}),foe=E.make(s,'neutral0',{attack:1,health:1}),r=E.combat(s,[guard,source],[foe]);A.deepEqual(r.permanent[0][guard.uid],{attack:4,health:8});});
test('shield deathrattle shields distinct allies; spell deathrattle supports golden and echo',()=>{const s=fresh(),source=E.make(s,'neutral21',{attack:0,health:1,golden:true,keywords:['taunt']}),allies=[quiet(s,'neutral0'),quiet(s,'neutral1')],r=E.combat(s,[source,...allies],[E.make(s,'neutral0',{attack:100000,health:100000})]);A.equal(r.events.filter(e=>e.kind==='shield'&&e.text.includes('谢幕')).length,2);for(const golden of [false,true]){const t=fresh(),c=E.make(t,'neutral12',{attack:0,health:1,golden,keywords:['taunt']}),q=E.combat(t,[c,quiet(t,'neutral15')],[E.make(t,'neutral0',{attack:100000,health:100000})],{tier:4});A.equal(q.generated[0].length,golden?4:2);A(q.generated[0].every(id=>D.byId[id].type==='spell'&&D.byId[id].tier<=4&&E.available(t,D.byId[id])));}});
test('power growth uses integers, rounds base gains up, and doubles golden gains',()=>{const s=fresh();play(s,'rune12');A.equal(s.progress.spellcraft,1);play(s,'rune12',{golden:true});A.equal(s.progress.spellcraft,3);s.board=[E.make(s,'rune17')];E.endRecruit(s);A.equal(s.progress.spellcraft,6);A.equal(S.prayer({progress:{prayers:3}}),0);A.equal(S.prayer({progress:{prayers:4}}),1);for(const golden of [false,true]){const t=fresh();play(t,'haven15',{golden});A.equal(t.progress.devotion,golden?4:2);A(E.validate(t));}});
test('temple preview matches integer devotion and prayer boundary',()=>{for(const prayers of [2,3]){const s=fresh(),c=E.make(s,'neutral0');s.board=[c];s.progress.prayers=prayers;const view=S.amuletView(s,D.byId.temple),a=c.attack,h=c.health;s.amulets=[{...E.make(s,'temple'),count:1}];E.endRecruit(s);A.equal(c.attack-a,4+view.amp);A.equal(c.health-h,6+view.amp);A.equal(s.progress.devotion,2);A(E.validate(s));}});
test('Aether adds slots without accelerating; leaving retains existing amulets and blocks further placement',()=>{for(const golden of [false,true]){const s=fresh(),c=E.make(s,'haven25',{golden});s.board=[c];A.equal(S.amuletCapacity(s),golden?4:3);s.amulets=Array.from({length:S.amuletCapacity(s)},()=>({...E.make(s,'garden'),count:3}));const ended=JSON.parse(JSON.stringify(s));E.endRecruit(ended);A(ended.amulets.every(c=>c.count===2));A.equal(ended.hand.length,0);act(s,'sell',{uid:c.uid});A.equal(S.amuletCapacity(s),2);A(E.validate(JSON.parse(JSON.stringify(s))));const extra=E.make(s,'bell');s.hand=[extra];A.equal(E.act(s,'play',{uid:extra.uid}).ok,false);A.equal(s.hand.length,1);}const s=fresh();s.board=[E.make(s,'haven25'),E.make(s,'haven5'),E.make(s,'neutral16')];s.amulets=[{...E.make(s,'garden'),count:1}];E.endRecruit(s);A.equal(s.progress.prayers,1);A.equal(s.hand.length,2);A(s.hand.every(c=>D.byId[c.id].type==='amulet'));});
test('current discover lists and finite AI values cover replacement roles',()=>{const s=fresh();s.tribe='haven';s.route=0;s.board=[E.make(s,'haven8'),E.make(s,'haven20'),E.make(s,'haven6')];for(const id of ['haven8','haven20','haven25','neutral4','neutral12','haven23'])A(Number.isFinite(AI.synergyValue(s,E.make(s,id))),id);A(D.abilityIds.lastWords.includes('neutral21'));A(D.abilityIds.lastWords.includes('neutral12'));A(D.fanfareIds.includes('neutral4'));A(!D.abilityIds.endRecruit.includes('haven8'));A(D.abilityIds.endRecruit.includes('haven5'));A(!D.abilityIds.endRecruit.includes('haven25'));A.equal(D.byId.mine.tier,5);A.equal(S.growthAmount(s,'rallyCry'),2);});

test('avatar snapshots health for both stats; adjacent memory retains both, including golden and repeated rounds',()=>{
 for(const golden of [false,true])for(const memory of [null,false,true]){
  const s=fresh(),c=quiet(s,'haven16',{health:80,golden}),aura=memory===null?null:quiet(s,'haven20',{golden:memory}),board=aura?[c,aura]:[c];
  for(let round=0;round<2;round++){
   const before=E.copy(c),n=c.health*(golden?2:1),r=E.combat(s,board,[quiet(s,'neutral0')]),event=r.events.find(e=>e.text.includes('生命化身')),body=event.boards[0].find(x=>x.originUid===c.uid);
   A.equal(body.attack,c.attack+n);A.equal(body.health,c.health+n);A.equal(body.maxHealth,c.health+n);A.deepEqual(c,before);
   if(memory===null)A.equal(r.permanent[0][c.uid],undefined);
   else{const m=memory?2:1;A.deepEqual(r.permanent[0][c.uid],{attack:n*m,health:n*m});c.attack+=n*m;c.health+=n*m;}
  }
 }
 const s=fresh(),c=quiet(s,'haven16',{health:80}),r=E.combat(s,[c,quiet(s,'neutral0'),quiet(s,'haven20')],[quiet(s,'neutral0')]);A.equal(r.permanent[0][c.uid],undefined);
});
console.log(total+' inheritance groups passed; fixed scenarios, no AI games.');
