'use strict';
const A=require('node:assert/strict'),fs=require('fs'),E=require('./engine'),D=require('./data'),AI=require('./ai');let total=0;
function test(name,f){f();console.log('PASS '+name);total++;}
function fresh(){const s=E.create('angel',541,'hard',['night','dragon','blood','artifact']);Object.assign(s,{board:[],hand:[],shop:[],gold:20,tier:6});return s;}
const add=(s,id,extra={})=>{const c=E.make(s,id,extra);s.board.push(c);return c;};
function act(s,t,a={}){const r=E.act(s,t,a);A(r.ok,r.message);}
function play(s,id,extra={}){const c=E.make(s,id,extra);s.hand.push(c);act(s,'play',{uid:c.uid});return c;}
const quiet=(s,id)=>E.make(s,id,{attack:0,health:100000,keywords:['cannotAttack','stealth']});
const foe=s=>E.make(s,'neutral0',{attack:1000000,health:1000000});
test('official replacements, class counts and deliberate dual types',()=>{A.equal(D.cards.length,221);for(const t of D.tribeIds)A.equal(D.cards.filter(c=>c.tribe===t).length,t==='night'?26:t==='rune'?24:25);for(const r of require('./qa/reforged-art.json')){const d=D.byId[r.id];A.equal(d.name,r.name);A.equal(d.sourceId,r.sourceId);A.equal(d.originalType,1);A(fs.existsSync(d.art));}A.deepEqual(D.tribesOf('forest24'),['forest','rune']);A.deepEqual(D.tribesOf('royal22'),['royal']);A.deepEqual(D.tribesOf('dragon19'),['dragon']);A.deepEqual(D.tribesOf('blood23'),['blood','dragon']);A.equal(D.byId.night4.tier,4);A.equal(D.byId.night20.tier,3);A.equal(D.byId.royal23.tier,2);A(!D.cards.includes(D.byId.rune23));A(D.retiredCards.includes(D.byId.rune23));});
test('low-tier activation consumes chosen fuel exactly once, with golden multiplier',()=>{for(const golden of [false,true]){const s=fresh(),c=add(s,'dragon8',{golden}),fuel=E.make(s,'dragon22');s.hand=[fuel];const old=c.attack;act(s,'activate',{uid:c.uid,discardUid:fuel.uid});A.equal(c.attack-old,3*(golden?2:1));A.equal(s.gold,20);A.equal(s.stats.discards,1);A.deepEqual(s.hand.map(c=>c.id),['dragonWing','dragonWing']);A(!E.act(s,'activate',{uid:c.uid,discardUid:s.hand[0].uid}).ok);A(E.validate(s));}});
test('sale rewards normal amounts, discard rewards double, no sale counted as discard',()=>{for(const golden of [false,true])for(const discarded of [false,true])for(const id of ['dragon22','dragon23']){const s=fresh(),target=add(s,'neutral0',{health:1}),c=E.make(s,id,{golden}),m=(golden?2:1)*(discarded?2:1);if(discarded)s.hand=[c];else s.board.push(c);act(s,discarded?'discard':'sell',{uid:c.uid});A.equal(s.stats.discards,discarded?1:0);A.equal(s.gold,discarded?20:21);if(id==='dragon22')A.equal(s.hand.length,m);if(id==='dragon23')A.equal(s.progress.tavernAttack,2*m);A(E.validate(s));}});
test('full hand and empty board departure rewards terminate safely',()=>{const s=fresh(),c=add(s,'dragon22',{golden:true});s.hand=Array.from({length:10},()=>E.make(s,'coin'));act(s,'sell',{uid:c.uid});A.equal(s.hand.length,10);const x=E.make(s,'dragon19');s.hand=[x];act(s,'discard',{uid:x.uid});A.equal(s.board.length,0);A(E.validate(s));});
test('destiny supplier creates usable targeted discard spell; no end-of-turn triple',()=>{const s=fresh();add(s,'dragon12');s.hand=[E.make(s,'dragon23')];E.endRecruit(s);A.equal(s.hand[1].id,'newDestiny');s.recruitEnded=false;act(s,'play',{uid:s.hand[1].uid});A.equal(s.discover[0].type,'discard');act(s,'choose',{id:String(s.hand[0].uid)});A.equal(s.hand.length,2);A.equal(s.progress.tavernAttack,4);A(s.hand.every(c=>D.byId[c.id].type==='spell'&&D.byId[c.id].tier<=2));});
test('Pydon ignores discards and adds a fixed tavern bonus then buffs both adjacent allies',()=>{for(const golden of [false,true]){const s=fresh(),l=add(s,'neutral0'),p=add(s,'dragon24',{golden}),r=add(s,'neutral1'),m=golden?2:1;s.progress.tavernAttack=20;s.progress.tavernHealth=12;s.hand=[E.make(s,'coin')];act(s,'discard',{uid:s.hand[0].uid});A.equal(s.progress.tavernAttack,20);const before=E.copy([l,r]);E.endRecruit(s);A.equal(s.progress.tavernAttack,20+4*m);A.equal(s.progress.tavernHealth,12+4*m);for(let i=0;i<2;i++){A.equal([l,r][i].attack-before[i].attack,(20+4*m)*m);A.equal([l,r][i].health-before[i].health,(12+4*m)*m);}A.equal(p.attack,7);for(let round=0;round<4;round++){s.recruitEnded=false;const before=s.progress.tavernAttack;E.endRecruit(s);A.equal(s.progress.tavernAttack-before,4*m);} A.match(E.scaling.formulaText(s,p,D.byId.dragon24.text),/当前/);}});
test('grave discover spends a fixed amount, respects open tribes and golden repetitions',()=>{for(const golden of [false,true]){const s=fresh();s.grave=3;s.tier=3;play(s,'night11',{golden});A.equal(s.grave,0);A.equal(s.discover.length,golden?2:1);for(const q of s.discover)for(const id of q.options){A(D.abilityIds.lastWords.includes(id));A(D.byId[id].tier<=4);A(E.available(s,D.byId[id]));}A(E.validate(s));}const t=fresh();play(t,'night11');A.equal(t.discover.length,0);});
test('food for souls spends four grave only when it can grow neighbors',()=>{for(const golden of [false,true]){const s=fresh(),l=add(s,'neutral0'),c=add(s,'night21',{golden}),r=add(s,'dragon0');s.grave=5;s.progress.battleEntries=30;const a=l.attack;E.endRecruit(s);A.equal(s.grave,1);A.equal(l.attack-a,9*(golden?2:1));A.equal(c.attack,4);A.equal(r.attack,D.byId.dragon0.attack+9*(golden?2:1)+1);A(E.validate(s));}const t=fresh();add(t,'night21');t.grave=5;E.endRecruit(t);A.equal(t.grave,5);});
test('Andrealphus revives once, yielding three grave on each death',()=>{const s=fresh(),r=E.combat(s,[E.make(s,'night8',{attack:0,health:1})],[foe(s)]);A.equal(r.deadCount[0],2);A.equal(r.grave[0],8);A.equal(r.progress[0].battleEntries,1);});
test('rebirth provider grants two units or four golden, across tribes',()=>{for(const golden of [false,true]){const s=fresh(),r=E.combat(s,[...Array.from({length:4},()=>quiet(s,'neutral0')),E.make(s,'night15',{golden,attack:0,keywords:['cannotAttack']})],[quiet(s,'neutral0')]);const start=r.events.find(e=>e.text.includes('开战效果结算完成'));A.equal(start.boards[0].filter(c=>c.reborn).length,golden?4:2);}});
test('Nephthys costs three and reserves full-body revival before a summoning deathrattle',()=>{const s=fresh(),victim=E.make(s,'night5',{attack:0,health:1,keywords:['taunt']}),neph=quiet(s,'night7'),board=[victim,neph,...Array.from({length:5},()=>quiet(s,'neutral0'))],r=E.combat(s,board,[foe(s)],{grave:2});const returned=r.events.find(e=>e.kind==='summon'&&e.text.startsWith('复活 ')&&e.boards[0].some(x=>x.id==='night5'&&x.resurrected));A(returned);A.equal(returned.boards[0].length,7);A.equal(r.events.filter(e=>e.kind==='summon'&&e.text.startsWith('复活 ')&&e.boards[0].some(x=>x.id==='night5'&&x.resurrected)).length,1);A(r.grave[0]>=0);});
test('legion health gains flat six plus double legion, ordinary and golden',()=>{for(const golden of [false,true]){const s=fresh(),r=E.combat(s,[E.make(s,'night23',{attack:0,health:1,keywords:['taunt']}),{...quiet(s,'night24'),golden}],[foe(s)],{progress:{legionAttack:10}});A(r.events.some(e=>e.kind==='summon'&&e.boards[0].some(c=>c.id==='skeleton'&&c.health===1+26*(golden?2:1))));}});
test('Stella returns one spell per copy with tier based on distinct names',()=>{for(const golden of [false,true])for(const spells of [0,2,5]){const s=fresh();add(s,'rune21',{golden});s.spellNamesThisRound=['coin','mana','growth','mining','clock'].slice(0,spells).map(id=>D.byId[id].name);E.endRecruit(s);A.equal(s.hand.length,golden?2:1);A(s.hand.every(c=>D.byId[c.id].tier===Math.min(6,spells+1)));}});
test('small consumer eats once, pays one HP and rounds each half stat upward',()=>{for(const golden of [false,true]){const s=fresh(),c=add(s,'blood5',{golden});s.shop=[E.make(s,'neutral0',{attack:7,health:9})];const before=E.copy(c),frames=E.endRecruit(s,true),m=golden?2:1;A.equal(c.attack-before.attack,4*m);A.equal(c.health-before.health,5*m);A.equal(s.hp,39);A.equal(s.shop.length,0);A.equal(s.feasts.length,1);A(frames.some(f=>f.state.feasts.length));A.equal(s.gold,20);}});
test('large consumer only eats and grows itself, even at one hero health',()=>{for(const golden of [false,true])for(const hp of [1,40]){const s=fresh(),c=add(s,'blood24',{golden}),ally=add(s,'neutral0'),m=golden?2:1;s.shop=[E.make(s,'neutral0',{attack:9,health:12}),E.make(s,'neutral1',{attack:6,health:9})];s.hp=hp;const before=E.copy([c,ally]);E.endRecruit(s);A.equal(s.hp,hp);A.equal(s.bloodDamage,0);A.equal(s.shop.length,0);A.equal(s.feasts.length,2);A.equal(c.attack-before[0].attack,15*m);A.equal(c.health-before[0].health,21*m);A.equal(ally.attack-before[1].attack,0);A.equal(ally.health-before[1].health,0);A(E.validate(s));}});
test('consume observers improve the second actual offer; empty shops do not self-harm',()=>{const s=fresh(),c=add(s,'blood24');add(s,'blood23');s.shop=[E.make(s,'neutral0',{attack:9,health:12}),E.make(s,'neutral0',{attack:6,health:9})];E.endRecruit(s);A.equal(s.progress.tavernAttack,4);A.equal(s.feasts[1].food.attack,8);A.equal(c.attack,24);const t=fresh();add(t,'blood24');add(t,'blood5');E.endRecruit(t);A.equal(t.hp,40);});
test('relic replacement dies for scrap and arms and never has discarded economy',()=>{const s=fresh(),r=E.combat(s,[E.make(s,'artifact19',{attack:0,health:1})],[foe(s)]);A.equal(r.scrap[0],3);A.equal(r.progress[0].arms,1);s.hand=[E.make(s,'artifact19')];act(s,'discard',{uid:s.hand[0].uid});A.equal(s.scrap,0);A.equal(s.progress.arms,0);});
test('static AI values finite and exported saves validate after changed effects',()=>{const s=fresh();s.tribe='dragon';s.route=1;s.grave=9;s.scrap=9;s.board=[E.make(s,'neutral0')];for(const id of ['night11','night21','night24','night7','dragon8','dragon12','dragon19','dragon24','blood5','blood24','artifact19','rune21']){const c=E.make(s,id);A(Number.isFinite(AI.synergyValue(s,c)),id);A(!/NaN|undefined/.test(E.scaling.formulaText(s,c,D.byId[id].text)));}s.hand=[E.make(s,'rune23')];A(E.validate(E.normalize(E.copy(s))));A(!E.pool(s,D.cards).some(c=>c.id==='rune23'));s.discover=[{type:'minion',title:'旧三连奖励',text:'旧存档选项',options:['rune23']}];A(E.validate(s));act(s,'choose',{id:'rune23'});A.equal(s.hand.length,2);const old=add(s,'artifact19',{keywords:[]});E.normalize(s);A(old.keywords.includes('taunt'));});
console.log(total+' reforged groups passed; fixed scenarios only, no AI matches.');
