'use strict';
const A=require('node:assert/strict'),D=require('./data'),E=require('./engine'),AI=require('./ai'),Echo=require('./echoes');let passed=0;
const test=(name,fn)=>{fn();console.log('PASS '+name);passed++;};
function state(){const s=E.create('angel',72635,'hard',['forest','rune','dragon','blood']);s.board=[];s.hand=[];s.shop=[];s.gold=30;s.tier=3;return s;}
const add=(s,id,x={})=>{const c=E.make(s,id,x);s.board.push(c);return c;};
function act(s,t,x={}){const r=E.act(s,t,x);A(r.ok,r.message);}
function play(s,id,target){const c=E.make(s,id);s.hand.push(c);act(s,'play',{uid:c.uid,target:target??s.board[0]?.uid});return c;}
test('mirror is retired and majority discovery counts dual tribes and respects current tavern tier',()=>{const s=state();A(D.byId.mirrorRecruit.retired);A(!D.spells.includes(D.byId.mirrorRecruit));add(s,'forest24');add(s,'rune0');add(s,'forest0');A.deepEqual(D.majorityTribes(s),['forest','rune']);const pool=D.discoveryPool(s,D.byId.seekMajority);A(pool.some(c=>c.tier===3));A(pool.every(c=>c.tier<=3&&(D.isTribe(c,'forest')||D.isTribe(c,'rune'))));play(s,'seekMajority');A(E.validate(s));A.equal(s.discover[0].options.length,3);const empty=state(),c=E.make(empty,'seekMajority');empty.hand=[c];A(!E.act(empty,'play',{uid:c.uid}).ok);A(empty.hand.includes(c));});
test('minion discovery stays within tavern tier; researcher covers four through six',()=>{const s=state();for(const id of ['seekCry','seekLast','seekEnd','royal21','night11']){s.activeTribes=['royal','night','rune','dragon'];const pool=D.discoveryPool(s,D.byId[id]);A(pool.every(c=>c.tier<=3));A(pool.some(c=>c.tier===3),id);}A(D.discoveryPool(s,D.byId.seekRecruit).every(c=>c.tier===3));s.tier=6;A(D.discoveryPool(s,D.byId.seekRecruit).every(c=>c.tier===6));const high=D.discoveryPool(s,D.byId.rune20);A.deepEqual([...new Set(high.map(c=>c.tier))].sort(),[4,5,6]);});
test('gold cap directly increases with no instant gold; old mining saves retain whole cap increases',()=>{const s=state();s.progress.mining=8;delete s.progress.goldCapBonus;E.normalize(s);A.equal(s.progress.goldCapBonus,2);A(!('mining' in s.progress));A.equal(E.scaling.goldCap(s),12);A.equal(D.byId.mining.cost,3);const gold=s.gold;play(s,'mining');A.equal(s.gold,gold);A.equal(E.scaling.goldCap(s),13);s.round=8;E.startRound(s);A.equal(s.gold,13);s.amulets=[{...E.make(s,'mine'),count:1}];E.endRecruit(s);A.equal(E.scaling.goldCap(s),15);A.equal(s.gold,13);A(E.validate(s));});
test('treasure hunter pays finite coins from actual spending, including refresh and upgrade',()=>{const s=state();add(s,'neutral18');s.shop=[E.make(s,'neutral1')];act(s,'buy',{uid:s.shop[0].uid});for(let i=0;i<5;i++)act(s,'refresh');A.equal(s.goldSpentThisRound,8);E.endRecruit(s);A.equal(s.hand.filter(c=>c.id==='coin').length,1);A.equal(E.scaling.goldCap(s),10);E.endRecruit(s);A.equal(s.hand.filter(c=>c.id==='coin').length,1);});
test('Stella counts distinct names, ignores duplicate casts, supports golden and resets',()=>{const s=state();add(s,'rune21');play(s,'coin');play(s,'coin');play(s,'mana');A.equal(s.spellNamesThisRound.length,2);E.endRecruit(s);A.equal(s.hand.length,1);A.equal(D.byId[s.hand[0].id].tier,3);s.round++;E.startRound(s);A.deepEqual(s.spellNamesThisRound,[]);s.hand=[];s.board[0].golden=true;E.endRecruit(s);A.equal(s.hand.length,2);A(s.hand.every(c=>D.byId[c.id].tier===1));const t=state();add(t,'rune21');t.spellNamesThisRound=['a','b','c','d','e','f'];E.endRecruit(t);A.equal(D.byId[t.hand[0].id].tier,6);});
test('dragon spell doubles discarded-card payload only, not sales or discard observers',()=>{const s=state(),rally=add(s,'dragon21'),base=rally.attack;play(s,'discardEcho');play(s,'discardEcho');s.hand=[E.make(s,'dragon22')];act(s,'discard',{uid:s.hand[0].uid});A.equal(s.hand.filter(c=>c.id==='dragonWing').length,4);A.equal(s.stats.discards,1);A(rally.attack>base);const before=s.progress.tavernAttack;const c=add(s,'dragon23');act(s,'sell',{uid:c.uid});A.equal(s.progress.tavernAttack-before,2);s.hand=[E.make(s,'dragon23')];act(s,'discard',{uid:s.hand[0].uid});A.equal(s.progress.tavernAttack-before,10);E.endRecruit(s);A.equal(s.discardEcho,false);});
test('opening payoffs have full card count, both stats and cross-tribe receivers; remain temporary',()=>{for(const id of ['forest23','blood7','artifact7']){const s=state(),source=E.make(s,id,{attack:0,health:10000,keywords:['cannotAttack']}),ally=E.make(s,'neutral0',{attack:0,health:10000,keywords:['cannotAttack']}),foe=E.make(s,'neutral0',{attack:0,health:10000,keywords:['cannotAttack']});const meta={progress:{totalPlayed:60},bloodDamage:30,scrap:40},r=E.combat(s,[source,ally],[foe],meta),frame=r.events.find(e=>e.text.includes('开战效果结算完成')),c=frame.boards[0].find(c=>c.uid===ally.uid),n=id==='artifact7'?120:60;A.equal(c.attack,n);A.equal(c.health,10000+n);A.equal(ally.attack,0);A.equal(r.permanent[0][ally.uid],undefined);}});
test('AI evaluates whole formations, avoids echo recursion and plans a single late recruitment',()=>{const s=state();s.round=12;s.tribe='rune';s.route=1;s.spells=50;s.progress.spellcraft=40;s.board=['rune15','rune18','rune6','rune3','neutral0','neutral1','neutral2'].map(id=>E.make(s,id,{attack:35,health:35}));const core=E.make(s,'rune5');const decision=AI.replacement(s,core,AI.plans.rune[1]);A(Number.isFinite(decision.gain));const t=state();t.tribe='rune';t.route=0;t.board=['neutral16','neutral16','rune3'].map(id=>E.make(t,id));A(Number.isFinite(AI.boardValue(t,AI.plans.rune[0])));const o=s.opponents[0];Object.assign(o,{hero:'rune',tribe:'rune',route:1,board:s.board,hand:[core,E.make(s,'grandBlessing')],shop:[],gold:0,tier:6,progress:s.progress,spells:50,spellsThisRound:5});AI.prepare(s,o,E,{started:true,bonusGold:false,deferEnd:true});A(o.spells>50);A(o.board.some(c=>c.id==='rune5'));A(o.aiSummary.actions<200);console.log('  fixed late turn:',o.aiSummary.actions,'actions,',o.aiSummary.spellsCast,'spells,',o.aiSummary.boardPower,'total stats');});
test('local echoes validate, persist, exclude own run, match rules/pool/round and enforce 32 uses',()=>{const mem=new Map(),storage={getItem:k=>mem.get(k),setItem:(k,v)=>mem.set(k,v)},archive=Echo.create(storage),s=state();s.echoRunId='first-run';add(s,'neutral0');E.endRecruit(s);A(archive.capture(s));A(!archive.capture(s));archive.setEnabled(true);A.equal(archive.take(s),null);const t=state();t.echoRunId='second-run';for(let i=0;i<32;i++){const record=archive.take(t);A(record);A(archive.apply(t,record));A.equal(t.opponents.find(o=>o.id===t.opponent).echoRound,1);A(E.validate(t));}A.equal(archive.take(t),null);const loaded=Echo.create(storage);A.equal(loaded.stats().available,0);const raw=loaded.export();raw.records[0].uses=0;loaded.ingest(raw);A.equal(loaded.stats().available,0);raw.records[0].board[0].attack=-1;A.throws(()=>loaded.ingest(raw));const other=Echo.create({getItem:()=>null,setItem:()=>{}});A.equal(other.ingest(archive.export()),1);});
console.log(passed+' renewal groups passed; fixed scenarios only, no full AI games.');
