'use strict';
const A=require('node:assert/strict'),E=require('./engine'),D=require('./data'),S=E.scaling;let passed=0;
const test=(name,fn)=>{fn();passed++;console.log('PASS '+name);};
const fresh=()=>{const s=E.create('angel',8513,'normal',['forest','haven','rune','dragon']);s.tier=6;s.gold=10;s.board=[];s.hand=[];s.shop=[];return s;};
const play=(s,id,target)=>{const c=E.make(s,id);s.hand.push(c);const r=E.act(s,'play',{uid:c.uid,target});A(r.ok,r.message);return c;};
test('long combos scale at 3/6/9/12 cards, golden doubles, no resource or army production',()=>{
 for(const golden of [false,true]){const s=fresh(),m=golden?2:1;s.board=[E.make(s,'forest1',{golden}),E.make(s,'forest4',{golden}),E.make(s,'forest3'),E.make(s,'neutral0')];const old=E.copy(s.board);let bug=0,team=0;
  for(let n=1;n<=12;n++){play(s,'bones');if(n%3===0){bug+=n*m;team+=(6+n)*m;}A.equal(s.board[0].attack-old[0].attack,bug+team);A.equal(s.board[0].health-old[0].health,bug+team);A.equal(s.board[1].attack,old[1].attack);A.equal(s.board[2].attack-old[2].attack,team);A.equal(s.board[3].attack-old[3].attack,team);A.equal(s.board[3].health-old[3].health,team);A.equal(s.gold,10);A.equal(s.hand.length,0);A.equal(s.progress.fairy,0);}A.equal(bug,30*m);A.equal(team,54*m);
 }
});
test('round reset clears combo ramp but keeps accumulated permanent stats',()=>{const s=fresh();s.board=[E.make(s,'forest1')];for(let i=0;i<9;i++)play(s,'bones');const a=s.board[0].attack;A.equal(a,D.byId.forest1.attack+18);s.round++;E.startRound(s);A.equal(s.played,0);for(let i=0;i<3;i++)play(s,'bones');A.equal(s.board[0].attack,a+3);});
test('saved long combo retains counter and next payout; token, spell and amulet each count once',()=>{const s=fresh();s.board=[E.make(s,'forest1'),E.make(s,'forest4')];s.played=8;const t=E.copy(s);E.normalize(t);A(E.validate(t));play(t,'fairy');A.equal(t.played,9);A.equal(t.board[0].attack-s.board[0].attack,9+15);play(t,'bones');play(t,'bell');play(t,'bones');A.equal(t.played,12);A.equal(t.board[0].attack-s.board[0].attack,9+15+12+18);});
test('buy, sell, refresh, activation and failed play cannot farm combo triggers',()=>{const s=fresh();s.played=2;s.board=[E.make(s,'forest1'),E.make(s,'rune19')];s.shop=[E.make(s,'neutral1')];const a=s.board[0].attack;A(E.act(s,'buy',{uid:s.shop[0].uid}).ok);A(E.act(s,'activate',{uid:s.board[1].uid}).ok);A(E.act(s,'sell',{uid:s.board[1].uid}).ok);A(E.act(s,'refresh').ok);A(!E.act(s,'play',{uid:-999}).ok);A.equal(s.played,2);A.equal(s.board[0].attack,a);});
test('seven fast amulets finish on next countdown, existing saved countdowns are retained',()=>{for(const id of ['garden','banner','bell','fairyGlade','hourglass','boneRing','summit']){const s=fresh();A.equal(D.byId[id].count,1);A(D.byId[id].text.startsWith('倒数 1'));play(s,id);A.equal(s.amulets[0].count,1);E.endRecruit(s);A.equal(s.amulets.length,0);A.equal(s.progress.prayers,1);const old=fresh();old.amulets=[{...E.make(old,id),count:2}];E.normalize(old);A.equal(old.amulets[0].count,2);}});
test('fairy glade remains two paid resources with no positive gold loop',()=>{const s=fresh();s.shop=[E.make(s,'fairyGlade')];A(E.act(s,'buyPlay',{uid:s.shop[0].uid}).ok);A.equal(s.gold,8);E.endRecruit(s);A.deepEqual(s.hand.map(c=>c.id),['fairy','fairy']);for(const c of [...s.hand]){A(E.act(s,'play',{uid:c.uid}).ok);A(E.act(s,'sell',{uid:c.uid}).ok);}A.equal(s.gold,10);A.equal(s.hand.length,0);A.equal(s.amulets.length,0);});
test('new temple cultivation is used by its own payload and later slot',()=>{const s=fresh();s.progress.prayers=1;s.board=[E.make(s,'neutral0')];const before=E.copy(s.board[0]);s.amulets=['temple','egg'].map(id=>({...E.make(s,id),count:1}));A(S.amuletView(s,D.byId.temple).short.includes('+7/+9'));E.endRecruit(s);A.equal(s.board[0].attack-before.attack,7);A.equal(s.board[0].health-before.health,9);A.equal(s.progress.devotion,3);A.equal(s.progress.tavernAttack,10);});
test('cultivation and choir supports observe expiry once, echo repeats only payload',()=>{for(const golden of [false,true]){const s=fresh(),m=golden?2:1;s.board=[E.make(s,'haven13',{golden}),E.make(s,'haven17',{golden}),E.make(s,'neutral17')];const before=E.copy(s.board);s.amulets=[{...E.make(s,'bell'),count:1}];E.endRecruit(s);A.equal(s.progress.prayers,1);A.equal(s.progress.devotion,2*m);for(let i=0;i<3;i++){A.equal(s.board[i].attack-before[i].attack,(i<2?(4+2*m)*m:0));A.equal(s.board[i].health-before[i].health,6+(i<2?(4+2*m)*m:0));}}});
test('spellcraft field pays both stats, reads current research, preview equals resolution',()=>{const s=fresh();s.progress.spellcraft=11;s.progress.devotion=2;s.progress.prayers=2;s.board=[E.make(s,'rune0'),E.make(s,'forest0')];const old=E.copy(s.board);A.equal(S.amuletView(s,D.byId.magicField).short,'攻击最低两名 +22/+12');s.amulets=[{...E.make(s,'magicField'),count:1}];E.endRecruit(s);A.equal(s.board[0].attack-old[0].attack,22);A.equal(s.board[0].health-old[0].health,12);A.equal(s.board[1].attack-old[1].attack,22);A.equal(s.board[1].health-old[1].health,12);});
test('high resonance never inflates resource counts or army increments',()=>{for(const [id,key,n]of [['fairyRealm','fairy',6],['deathBanquet','legionAttack',6],['library','spellcraft',4]]){const s=fresh();s.progress.devotion=100;s.amulets=[{...E.make(s,id),count:1}];E.endRecruit(s);A.equal(s.progress[key],n);A.equal(s.hand.length,id==='library'?2:0);A.equal(s.gold,10);}});
console.log(passed+' targeted long-combo/amulet groups passed; no AI games.');
