'use strict';
const assert=require('node:assert/strict');const E=require('./engine.js'),D=require('./data.js');
let count=0;
function test(name,fn){fn();count++;console.log('PASS '+name);}
const newGame=(h='forest')=>E.create(h,123456,'normal');
const add=(s,id,extra={})=>{const c=E.make(s,id,extra);s.board.push(c);return c;};
const hand=(s,id)=>{const c=E.make(s,id);s.hand.push(c);return c;};
function ok(s,type,arg){const r=E.act(s,type,arg);assert.equal(r.ok,true,r.message);return r;}
test('every card and hero has a verified matching Shadowverse identity and local art',()=>{const fs=require('node:fs'),path=require('node:path'),I=require('./identity.js');for(const d of [...D.cards,...D.spells,...D.amulets,...D.tokens,...D.trinkets,...D.heroes]){assert.equal(typeof d.sourceId,'number');assert(d.art.endsWith('/'+d.sourceId+'.webp'));assert(fs.existsSync(path.resolve(__dirname,'..',d.art)));if(d.type){assert.equal(d.name,d.sourceName);}for(const r of d.related||[])if(r.id)assert(D.byId[r.id]);}assert.equal(D.heroes.find(h=>h.id==='forest').name,'亚里莎');assert.equal(D.byId.night5.name,'冥界守卫犬·凯尔贝洛斯');assert.equal(I.cards.hound.sourceId,900541040);});
test('drag purchase and placement validate before any spending; ordered insertion',()=>{const s=newGame();s.gold=20;const a=add(s,'royal0'),b=add(s,'dragon0');s.shop=[E.make(s,'forest0'),E.make(s,'growth')];const u=s.shop[0].uid;ok(s,'buyPlay',{uid:u,index:1});assert.equal(s.board[1].uid,u);assert.equal(s.gold,17);ok(s,'moveTo',{uid:b.uid,index:0});assert.equal(s.board[0].uid,b.uid);const before=JSON.stringify(s);assert.equal(E.act(s,'buyPlay',{uid:s.shop[0].uid}).ok,false);assert.equal(JSON.stringify(s),before);while(s.board.length<7)add(s,'fairy');s.shop=[E.make(s,'royal2')];const full=JSON.stringify(s);assert.equal(E.act(s,'buyPlay',{uid:s.shop[0].uid}).ok,false);assert.equal(JSON.stringify(s),full);});
test('Cerberus summons both real tokens and triggers their separate death effects',()=>{const s=newGame();const r=E.combat(s,[E.make(s,'night5')],[E.make(s,'dragon0',{attack:3,health:50})],{tier:4},{tier:4});assert(r.events.some(e=>e.kind==='summon'&&e.text.includes('米米')));assert(r.events.some(e=>e.kind==='summon'&&e.text.includes('可可')));assert(r.events.some(e=>e.kind==='effect'&&e.text.includes('米米')&&e.text.includes('2 点伤害')));const gold=E.combat(s,[E.make(s,'night5',{golden:true,attack:12,health:12})],[E.make(s,'dragon0',{attack:4,health:100})],{tier:4},{tier:4});assert(gold.events.some(e=>e.kind==='summon'&&e.text.includes('米米')&&e.text.includes('8/8')));assert(gold.events.some(e=>e.kind==='effect'&&e.text.includes('米米')&&e.text.includes('4 点伤害')));});
test('catalog: all 160 minions, six tiers, complete images/effects',()=>{assert.equal(D.cards.length,169);assert.equal(D.spells.length,19);assert.equal(D.amulets.length,10);assert.equal(D.trinkets.length,0);for(const t of Object.keys(D.tribes))assert.deepEqual([...new Set(D.cards.filter(c=>c.tribe===t).map(c=>c.tier))],[1,2,3,4,5,6]);assert.equal(Object.keys(D.byId).length,D.cards.length+D.spells.length+D.retiredSpells.length+D.amulets.length+D.tokens.length);});
test('seeded shop and invalid purchase are deterministic and transactional',()=>{const a=newGame(),b=newGame();assert.deepEqual(a,b);a.gold=0;const before=JSON.stringify(a);assert.equal(E.act(a,'buy',{uid:a.shop[0].uid}).ok,false);assert.equal(JSON.stringify(a),before);});
test('buy, play, battlecry, sell economy',()=>{const s=newGame();s.shop=[E.make(s,'royal11')];ok(s,'buy',{uid:s.shop[0].uid});assert.equal(s.gold,0);ok(s,'play',{uid:s.hand[0].uid});assert.equal(s.board.length,1);assert.equal(s.hand[0].id,'knight');ok(s,'sell',{uid:s.board[0].uid});assert.equal(s.gold,1);});
test('targeted spell refuses invalid target without consuming the hand',()=>{const s=newGame('rune'),c=hand(s,'growth');const before=JSON.stringify(s);assert.equal(E.act(s,'play',{uid:c.uid}).ok,false);assert.equal(JSON.stringify(s),before);const target=add(s,'rune0');ok(s,'play',{uid:c.uid,target:target.uid});assert.equal(target.attack,6);assert.equal(target.health,7);assert.equal(s.spells,1);});
test('board and hand limits; free sell path when board is full',()=>{const s=newGame();for(const d of D.tokens.slice(0,7))add(s,d.id);const c=hand(s,'royal0');assert.equal(E.act(s,'play',{uid:c.uid}).ok,false);ok(s,'sell',{uid:s.board[0].uid});ok(s,'play',{uid:c.uid});assert.equal(s.board.length,7);for(let i=0;i<10;i++)hand(s,'mana');s.gold=10;assert.equal(E.act(s,'buy',{uid:s.shop[0].uid}).ok,false);});
test('triple merges across board/hand, retains buffs, and discovers higher tier',()=>{const s=newGame();add(s,'forest0',{attack:4,health:5});add(s,'forest0');hand(s,'forest0');E.triples(s);assert.equal(s.board.length,1);assert.equal(s.board[0].golden,true);assert.equal(s.board[0].attack,6);assert.equal(s.board[0].health,7);assert.equal(s.discover.length,1);for(const id of s.discover[0].options)assert.equal(D.byId[id].tier,2);ok(s,'choose',{id:s.discover[0].options[0]});assert.equal(s.hand.length,1);});
test('full hand cannot deadlock a triple reward',()=>{const s=newGame();for(let i=0;i<10;i++)hand(s,'mana');for(let i=0;i<3;i++)add(s,'royal0');E.triples(s);assert.equal(E.act(s,'choose',{id:s.discover[0].options[0]}).ok,false);ok(s,'discard',{uid:s.hand[0].uid});ok(s,'choose',{id:s.discover[0].options[0]});assert.equal(s.hand.length,10);assert.equal(s.discover.length,0);});
test('Light Path strengthens the entire formation without an extra resource',()=>{const s=newGame('dragon'),a=add(s,'dragon0'),b=add(s,'royal0');const before=[a,b].map(c=>[c.attack,c.health]);const spell=hand(s,'evo');ok(s,'play',{uid:spell.uid});[a,b].forEach((c,i)=>{assert.equal(c.attack,before[i][0]+1);assert.equal(c.health,before[i][1]+2);});assert.equal(s.spells,1);assert(!('evo' in s));});
test('freeze preserves unsold cards for one round; fresh budget and discount',()=>{const s=newGame();const uid=s.shop[0].uid;ok(s,'freeze');ok(s,'fight');ok(s,'continue');assert.equal(s.round,2);assert.equal(s.gold,4);assert(s.shop.some(c=>c.uid===uid));assert.equal(s.frozen,false);assert.equal(E.upgradeCost(s),4);});
test('amulet acceleration resolves and leaves its slot',()=>{const s=newGame('haven');const c=add(s,'haven0');const a=hand(s,'garden');ok(s,'play',{uid:a.uid});const spell=hand(s,'clock');ok(s,'play',{uid:spell.uid});assert.equal(s.amulets[0].count,1);s.gold=10;ok(s,'power');assert.equal(s.amulets.length,0);assert.equal(c.attack,5);assert.equal(c.health,8);});
test('legacy relic no longer doubles amulet payload',()=>{const s=newGame('haven');s.trinkets=['relic'];const c=add(s,'haven0');s.amulets=[{...E.make(s,'garden'),count:1}];ok(s,'power');assert.equal(c.attack,3);assert.equal(c.health,6);});
test('forest combo triggers once on each third played card',()=>{const s=newGame();const c=add(s,'forest1');for(let i=0;i<3;i++){const f=hand(s,'mana');ok(s,'play',{uid:f.uid,target:c.uid});}assert.equal(c.attack,12);assert.equal(c.health,8);});
test('combat attacks simultaneously, shield blocks and taunt is respected',()=>{const s=newGame();const a=E.make(s,'royal0',{attack:9,health:2}),b=E.make(s,'neutral0',{attack:8,health:5}),guard=E.make(s,'royal2',{attack:1,health:4});const r=E.combat(s,[a],[b,guard],{tier:1},{tier:1});const first=r.events.find(e=>e.kind==='attack');assert(first);if(first.from===100001)assert.equal(first.to,100003);assert.equal(a.health,2);assert(a.keywords.includes('shield'));assert(r.events.some(e=>e.kind==='death'));});
test('combat never mutates permanent stats, temporary buffs or keywords',()=>{const s=newGame();const left=[E.make(s,'royal7'),E.make(s,'royal0')],right=[E.make(s,'night5'),E.make(s,'dragon7')];const a=JSON.stringify(left),b=JSON.stringify(right);E.combat(s,left,right,{tier:6,trinkets:['crown','moon']},{tier:6});assert.equal(JSON.stringify(left),a);assert.equal(JSON.stringify(right),b);});
test('deathrattle, reborn, grave, and board cap',()=>{const s=newGame();const r=E.combat(s,[E.make(s,'night2'),E.make(s,'night5')],[E.make(s,'dragon7',{attack:100,health:100})],{tier:4},{tier:6});assert(r.deadCount[0]>=5);assert(r.grave[0]>=5);assert(r.events.every(e=>e.boards.every(b=>b.length<=7)));assert.equal(r.winner,1);assert(r.damage<=15);});
test('combat handles empty boards and zero-attack stalemates',()=>{const s=newGame();assert.equal(E.combat(s,[],[]).winner,-1);const r=E.combat(s,[E.make(s,'neutral0',{attack:0})],[E.make(s,'neutral0',{attack:0})]);assert.equal(r.winner,-1);assert(r.steps<=160);});
test('all spells and all heroes are actionable',()=>{for(const d of D.spells){const s=newGame();const c=add(s,d.effect==='module'?'artifact0':'dragon0');s.grave=10;const f=hand(s,d.id);ok(s,'play',{uid:f.uid,target:c.uid});assert(E.validate(s));}for(const h of D.heroes){const s=newGame(h.id),c=add(s,'royal0');s.gold=10;s.grave=10;ok(s,'power',{target:c.uid});assert.equal(s.powerUsed,true);assert.equal(E.act(s,'power',{target:c.uid}).ok,false);}});
test('all amulets resolve without state corruption',()=>{for(const a of D.amulets){const s=newGame('haven');add(s,'haven0');s.amulets=[{...E.make(s,a.id),count:1}];s.gold=10;ok(s,'power');assert.equal(s.amulets.length,0);assert(E.validate(s),a.name);}});
test('round four and eight no longer grant equipment',()=>{const s=newGame();for(const round of [4,8]){s.round=round;E.startRound(s);assert.equal(s.discover.length,0);assert.equal(s.trinkets.length,0);assert(E.validate(s));}});
test('damaged or wrong-shaped saves are rejected without throwing',()=>{assert.equal(E.validate(null),false);assert.equal(E.validate({}),false);const s=newGame();for(const [key,value] of [['round','<img>'],['board',[{id:'missing'}]],['trinkets',['unknown']],['stats',null],['opponents',[]],['phase','other'],['gold',NaN]])assert.equal(E.validate({...s,[key]:value}),false);ok(s,'fight');assert(E.validate(s));s.result.events[0].boards=null;assert.equal(E.validate(s),false);});
function autoPlay(seed,h,difficulty){const s=E.create(h,seed,difficulty);let n=0;while(s.phase!=='finished'&&n++<30){
 if(s.phase==='result'){ok(s,'continue');continue;}while(s.discover.length){if(s.hand.length>=10)ok(s,'discard',{uid:s.hand[0].uid});ok(s,'choose',{id:s.discover[0].options[0]});}
 if(s.tier<6&&s.gold>=E.upgradeCost(s)&&s.round%2===0)ok(s,'upgrade');
 let loops=0;while(loops++<30){while(s.discover.length){if(s.hand.length>=10)ok(s,'discard',{uid:s.hand[0].uid});ok(s,'choose',{id:s.discover[0].options[0]});}
 let played=false;for(const c of [...s.hand]){const d=D.byId[c.id];if(d.type==='minion'&&s.board.length>=7){const weak=s.board.reduce((a,b)=>a.attack+a.health<b.attack+b.health?a:b);if(c.attack+c.health>weak.attack+weak.health)ok(s,'sell',{uid:weak.uid});else continue;}if(d.type==='amulet'&&s.amulets.length>=2)continue;const target=d.effect==='module'?s.board.find(x=>D.byId[x.id].tribe==='artifact'):s.board[0];if(d.target&&!target)continue;ok(s,'play',{uid:c.uid,target:target?.uid});played=true;if(s.discover.length)break;}
 if(s.discover.length)continue;const affordable=s.shop.filter(c=>D.byId[c.id].cost<=s.gold&&s.hand.length<10&&(!D.byId[c.id].purchaseSelfHarm||s.hp>1)).sort((a,b)=>{const da=D.byId[a.id],db=D.byId[b.id];return (db.type==='minion'?db.tier*3+(db.tribe===h?4:0):0)-(da.type==='minion'?da.tier*3+(da.tribe===h?4:0):0);});if(affordable.length&&s.gold>0){ok(s,'buy',{uid:affordable[0].uid});continue;}if(s.gold>0&&s.hand.length<7){ok(s,'refresh');continue;}if(!played)break;
 }
 while(s.discover.length){if(s.hand.length>=10)ok(s,'discard',{uid:s.hand[0].uid});ok(s,'choose',{id:s.discover[0].options[0]});}ok(s,'fight');assert(E.validate(s));assert(s.result.events.every(e=>e.boards.every(b=>b.length<=7)));if(s.phase==='result')ok(s,'continue');
 }assert.equal(s.phase,'finished');assert(s.rank>=1&&s.rank<=8);return {hero:h,difficulty,round:s.round,rank:s.rank};}
test('264 full seeded games finish, preserve invariants, cover all heroes/difficulties',()=>{const results=[];for(const h of D.heroes)for(const d of ['easy','normal','hard'])for(let seed=1;seed<=4;seed++)results.push(autoPlay(seed*37429,h.id,d));const summary=Object.fromEntries(['easy','normal','hard'].map(d=>{const r=results.filter(x=>x.difficulty===d);return [d,{games:r.length,wins:r.filter(x=>x.rank===1).length,averageRank:+(r.reduce((n,x)=>n+x.rank,0)/r.length).toFixed(2),maxRound:Math.max(...r.map(x=>x.round))}];}));console.log(JSON.stringify(summary));assert.equal(results.length,264); /* Win feasibility is covered by equal-budget strategic play in ai-test.cjs. */});
console.log('\n'+count+' test groups passed.');
